## Prepare questions from ADNi for testing GRPO model

Created by: Sahana Kowshik

Date: 11/01/2025

In [1]:
import pandas as pd
import json
import random

In [2]:
directory_path = "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/adni"
test = pd.read_csv(f"{directory_path}/training_data/testing_data_grpo/test_summary.csv")

In [3]:
test['COHORT'] = "ADNI"

In [4]:
print(test.iloc[0]['visit_summary'])

The subject is a 70.6-year-old White, female participant who is not Hispanic or Latino and speaks English. She was born in July 1947 and has completed 16 years of education. Her family history reveals that both her biological parents have deceased, with the mother passing away at age 69 and the father at an unspecified age. Both parents had dementia, but neither had Alzheimer’s disease; symptoms began at age 65 for the mother and at age 67 for the father. In terms of health history, the participant has a variety of chronic conditions including hearing loss, hypothyroidism, hypertension, hyperlipidemia, GERD, dry eyes, rhinorrhea, rosacea, spinal stenosis, and depression. Additionally, she has a history of surgeries related to the removal of a pre-melanoma lesion, polyps, and a partial thyroidectomy due to a goiter. Codeine use has been associated with mood swings. Her current physical condition includes a weight of 86.8 kilograms, a systolic blood pressure of 140 mmHg, a diastolic blood pressure of 76 mmHg, a pulse rate of 64 beats per minute, and a respiratory rate of 18 breaths per minute. Her temperature is 36.3°C, measured orally.

In terms of cardiovascular disease, the Modified Hachinski scale indicates no abrupt onset of dementia, no stepwise deterioration, no somatic complaints, no emotional incontinence, no history of stroke, and no focal neurological symptoms or signs. However, a history of hypertension is noted, contributing a score of 1 out of a possible total. The Geriatric Depression Scale (GDS) results show that the participant is generally satisfied with her life, does not feel her life is empty, is in good spirits most of the time, and does not experience fear or feelings of helplessness. She prefers to stay at home rather than engage in new activities and does not feel full of energy, resulting in a total score of 2. The Functional Assessment Questionnaire (FAQ) indicates that she performs all assessed daily activities independently, with the exception of remembering appointments and medications, where she experiences some difficulty, resulting in a total score of 1.

Neuropsychological testing results include a Mini-Mental State Examination (MMSE) score of 27, indicating intact cognitive function, with only one incorrect response in copying a design. The Montreal Cognitive Assessment (MoCA) score is also 27, with errors in the serial 7 subtraction task and clock drawing, where the hands were incorrectly placed. The Clock Drawing Test results show that while the face and numbers were correctly drawn, symmetry and hand placement were incorrect, resulting in a total score of 3. The Auditory Verbal Learning Test (AVLT) shows consistent learning across trials with 10 words recalled on the final trial and 8 words recalled after a 30-minute delay. Category fluency for animals is strong with 24 correct responses. The Trail Making Test Part A and B were completed without errors, taking 31 and 69 seconds respectively. The Rey Auditory Verbal Learning Test (RAVLT) indicates an immediate recall score of 43, with a forgetting score of 4 and a percent forgetting of 40. The Alzheimer’s Neurocognitive Rating Scale (ANART) shows 12 total errors, and the Memory and Information Naming Test (MINT) results indicate 32 correct responses without cues and 0 with semantic cues.

Genetically, the subject has an APOE genotype of e3/e4. Imaging evidence from an MRI report, based on a GAMLSS model fitted to FastSurfer-derived regional brain volumes, indicates mild atrophy in the medial temporal region. The analysis used normative data from 2,087 healthy controls and excluded participants with neurodegenerative diseases or extreme brain volumes. Lower centile scores in lobar regions indicate greater atrophy, while higher centile scores in ventricular regions indicate enlargement. The findings suggest mild atrophy in the medial temporal lobe.

In [5]:
len(test)

1392

In [6]:
test.head()

,RID,DIAGNOSIS,PTGENDER,PTDOBMM,PTDOBYY,PTEDUCAT,PTTLANG,PTETHCAT,PTRACCAT,CENTILOIDS,...,PHC_pTau,AT_class,AGE_MRI,AMYLOID_PET_POSITIVE,brain_findings_summary,patient_summary,diag_summary,visit_summary_prompt,visit_summary,COHORT
0,6234,1.0,2.0,7,1947,16.0,1.0,2.0,5.0,19.0,...,NaN,NaN,70.639288,0,Medial Temporal region has mild atrophy,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",<|im_start|>user\nYou will receive patient dat...,"The subject is a 70.6-year-old White, female p...",ADNI
1,2308,2.0,1.0,4,1936,15.0,1.0,2.0,5.0,-6.0,...,NaN,A-T-,74.880219,0,No significant findings. Brain MRI appears age...,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",<|im_start|>user\nYou will receive patient dat...,The subject is a 74.88-year-old male participa...,ADNI
2,7042,1.0,2.0,6,1960,16.0,1.0,2.0,4.0,-4.0,...,NaN,NaN,61.727584,0,Medial Parietal region has mild atrophy; Infer...,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",<|im_start|>user\nYou will receive patient dat...,The subject is a 61.73-year-old Black or Afric...,ADNI
3,6147,1.0,1.0,6,1948,16.0,1.0,2.0,5.0,24.0,...,NaN,NaN,69.702943,1,Hippocampus region has mild atrophy,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",<|im_start|>user\nYou will receive patient dat...,The subject is a 69.7-year-old male born in Ju...,ADNI
4,4444,2.0,1.0,6,1934,18.0,1.0,2.0,5.0,30.0,...,NaN,NaN,77.705681,1,No significant findings. Brain MRI appears age...,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",<|im_start|>user\nYou will receive patient dat...,The patient is a 77.7-year-old male born in Ju...,ADNI

In [7]:
test['DIAGNOSIS'].isna().sum()

0

In [8]:
test['AMYLOID_PET_POSITIVE'].isna().sum()

0

In [9]:
test['DIAGNOSIS'].value_counts()

DIAGNOSIS
2.0    603
1.0    555
3.0    234
Name: count, dtype: int64

In [10]:
columns = ['ID', 'patient_summary', 'diag_summary', 'visit_summary', 'question', 'options', 'ground_truth', 'ground_truth_text', 'COHORT']

# Add cognitive status question

In [11]:
import random, string

# Question variants for cognitive status identification
cog_question_variants = [
    "Using the information provided, determine the patient's cognitive status.",
    "Identify the patient's cognitive status based on the given information.",
    "Based on the provided clinical details, classify the patient's cognitive status.",
    "From the information available, determine the correct cognitive status for the patient.",
    "Analyze the patient's information and identify their cognitive status."
]

# Original answer texts
COG_OPTION_TEXTS = [
    "Normal Cognition (NC)",
    "Mild Cognitive Impairment (MCI)",
    "Dementia (DE)"
]

# Mapping from NACCUDSD to the correct label text
COG_ANSWER_MAP = {
    1: COG_OPTION_TEXTS[0],
    2: COG_OPTION_TEXTS[1],
    3: COG_OPTION_TEXTS[2],
}

def add_cog_question(row, *, seed=None):
    rng = random.Random(seed if seed is not None else row.name)

    # 1️⃣ Random question phrasing
    row['question'] = rng.choice(cog_question_variants)

    # 2️⃣ Shuffle the answer options
    shuffled = COG_OPTION_TEXTS.copy()
    rng.shuffle(shuffled)
    letters = list(string.ascii_uppercase[:len(shuffled)])
    row['options'] = "\n".join(f"{ltr}. {opt}" for ltr, opt in zip(letters, shuffled))

    # 3️⃣ Determine correct answer letter
    correct_text = COG_ANSWER_MAP.get(row['DIAGNOSIS'], None)
    if correct_text in shuffled:
        row['ground_truth'] = letters[shuffled.index(correct_text)]
    else:
        row['ground_truth'] = None  # fallback for unrecognized codes
    
    row['ground_truth_text'] = correct_text

    return row

In [12]:
# Apply the function to the MCI training set
test_cog = test.apply(add_cog_question, axis=1)

In [13]:
test_cog['ground_truth_text'].value_counts()

ground_truth_text
Mild Cognitive Impairment (MCI)    603
Normal Cognition (NC)              555
Dementia (DE)                      234
Name: count, dtype: int64

In [14]:
test_cog["ID"] = test_cog["RID"]
test_cog = test_cog[columns]
print(len(test_cog))
test_cog = test_cog.dropna(how='any').reset_index(drop=True)
print(len(test_cog))

1392
1392

/scratch/ipykernel_225100/2269045022.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_cog["ID"] = test_cog["RID"]

In [15]:
test_cog['Q_TYPE'] = "Cognitive status"

In [16]:
test_cog.head()

,ID,patient_summary,diag_summary,visit_summary,question,options,ground_truth,ground_truth_text,COHORT,Q_TYPE
0,6234,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...","The subject is a 70.6-year-old White, female p...","From the information available, determine the ...",A. Dementia (DE)\nB. Normal Cognition (NC)\nC....,B,Normal Cognition (NC),ADNI,Cognitive status
1,2308,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",The subject is a 74.88-year-old male participa...,Identify the patient's cognitive status based ...,A. Mild Cognitive Impairment (MCI)\nB. Normal ...,A,Mild Cognitive Impairment (MCI),ADNI,Cognitive status
2,7042,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",The subject is a 61.73-year-old Black or Afric...,"Using the information provided, determine the ...",A. Mild Cognitive Impairment (MCI)\nB. Dementi...,C,Normal Cognition (NC),ADNI,Cognitive status
3,6147,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",The subject is a 69.7-year-old male born in Ju...,Identify the patient's cognitive status based ...,A. Mild Cognitive Impairment (MCI)\nB. Normal ...,B,Normal Cognition (NC),ADNI,Cognitive status
4,4444,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",The patient is a 77.7-year-old male born in Ju...,Identify the patient's cognitive status based ...,A. Dementia (DE)\nB. Normal Cognition (NC)\nC....,C,Mild Cognitive Impairment (MCI),ADNI,Cognitive status

In [17]:
test_cog.to_csv(f"{directory_path}/training_data/testing_data_grpo/with_summary/test_cog.csv", index=False)

# Amyloid

In [18]:
test['AMYLOID_PET_POSITIVE'].value_counts()

AMYLOID_PET_POSITIVE
0    715
1    677
Name: count, dtype: int64

In [19]:
test_pet = test[~test['AMYLOID_PET_POSITIVE'].isna()].copy().reset_index(drop=True)

In [20]:
json.loads(test_pet.iloc[1]['patient_summary'])

{'Subject Demographics': {'1. Participant Gender': 'Male',
  '2a. Participant Month of Birth': 4,
  '2b. Participant Year of Birth': 1936,
  '5. Participant Education': 15.0,
  '9. Language to be used for testing the Participant': 'English',
  '12. Ethnic Category': 'Not Hispanic or Latino',
  '13. Racial Categories': 'White',
  'Subject age at MRI acquisition': 74.88021902806297},
 'Subject Health History': {'Initial Health Assessment - Description of condition': 'Rhinoplasty, (Surgery: Yes), (Surgery Date: 1964-07-01); High Cholesterol, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Persistent), (Severity: Moderate), (Onset Date: 2010-07-02), (Ongoing: Yes); Hypertension, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Persistent), (Severity: Moderate), (Onset Date: 2006-07-02), (Ongoing: Yes); Chronic Fatigue Syndrome, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Persistent), (Severity: Moderate), (Onset Date: 1990-07-02), (Ongoing: Yes); Shortness of Breath, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Persistent), (Severity: Mild), (Onset Date: 2008-07-01), (Ongoing: Yes); Appendectomy, (Surgery: Yes), (Surgery Date: 1940-07-01); Bunionectomy, (Surgery: Yes), (Surgery Date: 2011-01-16); Prior Smoking Hx, (Surgery: No), (Present in 3 months prior to screening: No), (Onset Date: 1951-07-02), (Ongoing: No), (Cease Date: 1971-07-02); Benign Prostatic Hyperplasia, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Persistent), (Severity: Mild), (Onset Date: 2010-07-02), (Ongoing: Yes); Bilateral Hearing Loss due to nerve damage, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Persistent), (Severity: Moderate), (Onset Date: 1956-07-01), (Ongoing: Yes); Food allergy-Limes, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Persistent), (Severity: Mild), (Onset Date: 2006-07-02), (Ongoing: Yes); Osteoarthritis-both knees, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Persistent), (Severity: Moderate), (Onset Date: 1987-07-02), (Ongoing: Yes); Decreased Testosterone Levels, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Persistent), (Severity: Moderate), (Onset Date: 2010-07-02), (Ongoing: Yes); Insomnia, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Persistent), (Severity: Moderate), (Onset Date: 1996-07-01), (Ongoing: Yes); Hepatitis B, (Surgery: No), (Present in 3 months prior to screening: No), (Onset Date: 1984-07-01), (Ongoing: No), (Cease Date: 1984-07-01); Acid Reflux, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Persistent), (Severity: Moderate), (Onset Date: 2000-07-01), (Ongoing: Yes); Drug Allergy-Penicillin, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Persistent), (Severity: Moderate), (Onset Date: 1940-07-01), (Ongoing: Yes); Duodenal Erosion, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Persistent), (Severity: Moderate), (Onset Date: 1997-07-02), (Ongoing: Yes); Left Knee Arthroplasty, (Surgery: Yes), (Surgery Date: 2012-01-30); Restless Leg Syndrome, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Intermittent), (Severity: Mild), (Onset Date: 2012-02-15), (Ongoing: Yes); Mild Constipation, (Surgery: No), (Present in 3 months prior to screening: No), (Onset Date: 2012-02-01), (Ongoing: No), (Cease Date: 2012-02-15); Right Ankle Repair, (Surgery: Yes), (Surgery Date: 1968-07-01); Seasonal Allergies, (Surgery: No), (Present in 3 months prior to screening: Yes), (Chronicity: Intermittent), (Severity: Mild), (Onset Date: 2000-07-01), (Ongoing: Yes)'},
 'Physical': {'Vitals: 1a. Weight': 200.2,
  'Vitals: 1b. Weight Units': 'pounds',
  'Vitals: Systolic - mmHg': 119.0,
  'Vitals: Diastolic - mmHg': 68.0,
  'Vitals: 4. Seated Pulse Rate (per minute)': 62.0,
  'Vitals: 5. Respirations (per minute)': 14.0,
  'Vitals: 6a. Temperature': 98.2,
  'Vitals: 6b. Temperature Source': 'Oral',
  'Vitals: 6c. Temperature Units': 'Fahrenheit'},
 'Cardiovascular disease': {'Modified Hachinski: 1. Abrupt Onset of Dementia': 'Absent',
  'Modified Hachinski: 2. Stepwise Deterioration of Dementia': 'Absent',
  'Modified Hachinski: 3. Somatic Complaints': 'Absent',
  'Modified Hachinski: 4. Emotional Incontinence': 'Absent',
  'Modified Hachinski: 5. History of Hypertension': 'Present - 1 point',
  'Modified Hachinski: 6. History of Stroke': 'Absent',
  'Modified Hachinski: 7. Focal Neurologic Symptoms': 'Absent',
  'Modified Hachinski: 8. Focal Neurologic Signs': 'Absent',
  'Modified Hachinski: TOTAL SCORE': 1.0},
 'Neuropsychiatric Inventory Questionnaire (NPI-Q)': {'NPI-Q: Information Source': 'Telephone Call',
  'NPI-Q: Does {P} believe that others are stealing from him/her, or planning to harm him/her in some way?': 'No',
  'NPI-Q: Does {P} act as if he/she hears voices? Does he/she talk to people who are not there?': 'No',
  'NPI-Q: Is {P} stubborn and resistive to help from others?': 'No',
  'NPI-Q: Does {P} act as if he/she is sad or in low spirits? Does he/she cry?': 'No',
  'NPI-Q: Does {P} become upset when separated from you? Does he/she have any other signs of nervousness, such as shortness of breath, sighing, being unable to relax, or feeling excessively tense?': 'No',
  'NPI-Q: Does {P} appear to feel too good or act excessively happy?': 'No',
  'NPI-Q: Does {P} seem less interested in his/her usual activities and in the activities and plans of others?': 'No',
  "NPI-Q: Does {P} seem to act impulsively? For example, does {P} talk to strangers as if he/she knows them, or does {P} say things that may hurt people's feelings?": 'No',
  'NPI-Q: Is {P} impatient or cranky? Does he/she have difficulty coping with delays or waiting for planned activities?': 'Yes',
  'NPI-Q: I. Irritability/Lability:  Severity Ratings': '1 - Mild (noticeable, but not a significant change).',
  'NPI-Q: Does {P} engage in repetitive activities, such as pacing around the house, handling buttons, wrapping strings, or doing other things repeatedly?': 'No',
  'NPI-Q: Does {P} awaken you during the night, rise too early in the morning, or take excessive naps during the day?': 'No',
  'NPI-Q: Has {P} lost or gained weight, or had a change in the food he/she likes?': 'No',
  'NPI-Q: Total Score': 1.0},
 'Geriatric Depression Scale (GDS)': {'GDS: Information Source': 'Participant Visit',
  'GDS: 1. Are you basically satisfied with your life?': 'Yes (0)',
  'GDS: 2. Have you dropped many of your activities and interests?': 'No (0)',
  'GDS: 3. Do you feel that your life is empty?': 'No (0)',
  'GDS: 4. Do you often get bored?': 'No (0)',
  'GDS: 5. Are you in good spirits most of the time?': 'Yes (0)',
  'GDS: 6. Are you afraid that something bad is going to happen to you?': 'No (0)',
  'GDS: 7. Do you feel happy most of the time?': 'Yes (0)',
  'GDS: 8. Do you often feel helpless?': 'No (0)',
  'GDS: 9. Do you prefer to stay at home, rather than going out and doing new things?': 'No (0)',
  'GDS: 10. Do you feel you have more problems with memory than most?': 'Yes (1)',
  'GDS: 11. Do you think its wonderful to be alive now?': 'Yes (0)',
  'GDS: 12. Do you feel pretty worthless the way you are now?': 'No (0)',
  'GDS: 13. Do you feel full of energy?': 'No (1)',
  'GDS: 14. Do you feel that your situation is hopeless?': 'No (0)',
  'GDS: 15. Do you think that most people are better off than you are?': 'No(0)',
  'GDS: Total Score': 2.0},
 'Functional Assessment Questionnaire (FAQ)': {'FAQ: Information Source': 'Telephone Call',
  'FAQ: 1. Writing checks, paying bills, or balancing checkbook.': 'Normal (0)',
  'FAQ: 2. Assembling tax records, business affairs, or other papers.': 'Normal (0)',
  'FAQ: 3. Shopping alone for clothes, household necessities, or groceries.': 'Normal (0)',
  'FAQ: 4. Playing a game of skill such as bridge or chess, working on a hobby.': 'Normal (0)',
  'FAQ: 5. Heating water, making a cup of coffee, turing off the stove.': 'Normal (0)',
  'FAQ: 6. Preparing a balanced meal.': 'Normal (0)',
  'FAQ: 7. Keeping track of current events.': 'Normal (0)',
  'FAQ: 8. Paying attention to and understanding a TV program, book, or magazine.': 'Normal (0)',
  'FAQ: 9. Remembering appointments, family occasions, holidays, medications.': 'Normal (0)',
  'FAQ: 10. Traveling out of the neighborhood, driving, or arranging to take public transportation.': 'Normal (0)',
  'FAQ: Total Score': 0.0},
 'Neuropsychological Battery Summary Scores': {'MMSE: Score (date)': '1 - Correct',
  'MMSE: Score (year)': '1 - Correct',
  'MMSE: Score (month)': '1 - Correct',
  'MMSE: Score (day of the week)': '1 - Correct',
  'MMSE: Score (season)': '1 - Correct',
  'MMSE: Score (building)': '1 - Correct',
  'MMSE: Score (floor)': '1 - Correct',
  'MMSE: Score (city/town)': '1 - Correct',
  'MMSE: Score (county)': '1 - Correct',
  'MMSE: Score (state)': '1 - Correct',
  'MMSE: What is this? [Point to a watch]': '1 - Correct',
  'MMSE: What is this? [Point to a pencil or pen]': '1 - Correct',
  'MMSE: No ifs, ands, or buts': '1 - Correct',
  'MMSE: Takes in right hand': '1 - Correct',
  'MMSE: Folds in half': '1 - Correct',
  'MMSE: Puts on floor': '1 - Correct',
  'MMSE: Close your eyes': '1 - Correct',
  'MMSE: Please write a sentence': '1 - Correct',
  'MMSE: Please copy this design': '1 - Correct',
  'MMSE TOTAL SCORE': 29.0,
  'MoCA: Trails': 'Correct',
  'MoCA: Copy Cube': 'Correct',
  'MoCA: Draw Clock - Contour': 'Correct',
  'MoCA: Draw Clock - Number': 'Correct',
  'MoCA: Draw Clock - Hands': 'Correct',
  'MoCA: Lion': 'Correct',
  'MoCA: Rhinoceros': 'Correct',
  'MoCA: Camel': 'Correct',
  'MoCA: Immediate (#1): Face': 'Correct',
  'MoCA: Immediate (#1): Velvet': 'Incorrect',
  'MoCA: Immediate (#1): Church': 'Correct',
  'MoCA: Immediate (#1): Daisy': 'Correct',
  'MoCA: Immediate (#1): Red': 'Correct',
  'MoCA: Immediate (#2): Face': 'Correct',
  'MoCA: Immediate (#2): Velvet': 'Correct',
  'MoCA: Immediate (#2): Church': 'Correct',
  'MoCA: Immediate (#2): Daisy': 'Correct',
  'MoCA: Immediate (#2): Red': 'Correct',
  'MoCA: Digits Forward': 'Correct',
  'MoCA: Digits Backward': 'Correct',
  'MoCA: List of Letters/Tapping:  # Errors': 0.0,
  'MoCA: Serial 7: 1st Subtraction': 'Correct',
  'MoCA: Serial 7: 2nd Subtraction': 'Correct',
  'MoCA: Serial 7: 3rd Subtraction': 'Correct',
  'MoCA: Serial 7: 4th Subtraction': 'Correct',
  'MoCA: Serial 7: 5th Subtraction': 'Correct',
  'MoCA: Repeat Sentence: I only know that John is the one to help today.': 'Correct',
  'MoCA: Repeat Sentence: The cat always hid under the couch when dogs were in the room.': 'Correct',
  'MoCA: Letter Fluency - F: Total number of correct words': 5.0,
  'MoCA: Abstraction: train-bicycle': 'Correct',
  'MoCA: Abstraction: watch-ruler': 'Correct',
  'MoCA: Delayed: Face': 'Correct with Mult. Choice Cue',
  'MoCA: Delayed: Velvet': 'Correct with Category Cue',
  'MoCA: Delayed: Church': 'Correct with Mult. Choice Cue',
  'MoCA: Delayed: Daisy': 'Correct with Category Cue',
  'MoCA: Delayed: Red': 'Correct with Category Cue',
  'MoCA: Month': 'Correct',
  'MoCA: Year': 'Correct',
  'MoCA: Day': 'Correct',
  'MoCA: Place': 'Correct',
  'MoCA: City': 'Correct',
  'Clock Drawing - 1. Approximately circular face': 'Yes',
  'Clock Drawing - 2. Symmetry of number placement': 'Correct',
  'Clock Drawing - 3. Correctness of numbers': 'Correct',
  'Clock Drawing - 4. Presence of the two hands': 'Correct',
  'Clock Drawing - 5. Presence of the two hands, set to ten after eleven': 'Correct',
  'Clock Drawing - Total Score': 5.0,
  'Clock Drawing Copy - 1. Approximately circular face': 'Correct',
  'Clock Drawing Copy - 2. Symmetry of number placement': 'Correct',
  'Clock Drawing Copy - 3. Correctness of numbers': 'Correct',
  'Clock Drawing Copy - 4. Presence of the two hands': 'Correct',
  'Clock Drawing Copy - 5. Presence of the two hands, set to ten after eleven': 'Correct',
  'Clock Drawing Copy - Total Score': 5.0,
  'AVLT - Trial 1 Total': 4.0,
  'AVLT - Trial 1 Total Intrusions': 2.0,
  'AVLT - Trial 2 Total': 8.0,
  'AVLT - Trial 2 Total Intrusions': 1.0,
  'AVLT - Trial 3 Total': 12.0,
  'AVLT - Trial 3 Total Intrusions': 2.0,
  'AVLT - Trial 4 Total': 13.0,
  'AVLT - Traial 4 Total Intrusions': 1.0,
  'AVLT - Trial 5 Total': 11.0,
  'AVLT - Trial 5 Total Intrusions': 2.0,
  'AVLT - Trial 6 Total': 10.0,
  'AVLT - Trial 6 Total Intrusions': 3.0,
  'AVLT - List B Total': 4.0,
  'AVLT - List B Total Intrusions': 0.0,
  'Category Fluency (Animals) - Total Correct': 22.0,
  'Category Fluency (Animals) - Perseverations': 0.0,
  'Category Fluency (Animals) - Intrusions': 0.0,
  'Trail Making Part A - Time to Complete': 30.0,
  'Trail Making Part A - Errors of Commission': 0.0,
  'Trail Making Part A - Errors of Omission': 0.0,
  'Trail Making Part B - Time to complete': 108.0,
  'Trail Making Part B -Errors of Commission': 0.0,
  'Trail Making Part B - Errors of Omission': 0.0,
  '1. Boston Naming Test - Number of spontaneously given correct responses': 28.0,
  '2. Boston Naming Test - Number of semantic cues given': 2.0,
  '3. Boston Naming Test - Number of correct responses following a semantic cue': 0.0,
  '4. Boston Naming Test - Number of phonemic cues given': 2.0,
  '5. Boston Naming Test - Number of correct responses following a phonemic cue': 1.0,
  'Boston Naming Test - Total Number Correct (1+3)': 28.0,
  'AVLT - 30 Minute Delay Total': 5.0,
  'AVLT - Delayed Total Intrusions': 1.0,
  'AVLT - Delayed Recognition Score': 13.0,
  'AVLT - Delayed Recognition Errors': 3.0,
  'ANART Total Score (Total # of errors)': 6.0},
 'Genetics': {'APOE Genotype - Allele 1 (e2=2, e3=3, e4=4)': 3.0,
  'APOE Genotype - Allele 2 (e2=2, e3=3, e4=4)': 3.0},
 'Blood-based biomarkers': {'Plasma Tau 181 Measurements in pg/mL': 21.94},
 'Imaging evidence': {'MRI Report': {'MRI features extraction procedure': 'A Generalized Additive Model for Location, Scale, and Shape (GAMLSS) was fitted to FastSurfer-derived regional brain volumes acquired from 2,087 healthy controls, following the Brain charts for the human lifespan methodology published in Nature (2022). Data were aggregated from five independent cohorts, and the analysis included region-of-interest (ROI) volumes for the medial and lateral temporal lobes, medial and lateral parietal lobes, frontal, occipital lobes, as well as the inferior lateral ventricles and hippocampus. To ensure a robust normative reference, participants with any known neurodegenerative disease were excluded and subjects with extreme brain volumes (>3.5 absolute z-scores) were excluded during quality control prior to model fitting. The Brain Charts pipeline was implemented to model age- and sex-specific normative centile curves for each ROI. Centile scores (scaled 0–1) were computed for both healthy controls and patient samples. Abnormality was defined based on a one-sided z-score threshold: mild atrophy/enlargement for scores corresponding to 1 standard deviation (z=1), moderate for 1.5 SD (z=1.5), and severe for 2 SD (z=2). For all lobar ROIs, lower centiles indicated greater atrophy, while for ventricular ROIs, higher centiles indicated enlargement (i.e., abnormality). The resulting findings are as follows: ',
   'T1 MRI Findings': 'No significant findings. Brain MRI appears age-appropriate.'}}}

In [21]:
import random, string, json

# Keys related to amyloid biomarkers that should be removed from the patient summary
# pet_keys_remove = [
#     'Abnormally elevated amyloid on PET',
#     'Abnormally low amyloid in CSF',
#     'FDG-PET pattern of AD',
#     'Tau PET evidence for AD',
#     'Abnormally elevated CSF Tau or pTau'
# ]

pet_question_variants = [
    "Is the patient likely to have elevated amyloid pathology in the brain given the provided information?",
    "Does the patient likely have abnormal amyloid accumulation in the brain based on the clinical data?",
    "Based on the available information, is the patient likely amyloid positive in the brain?",
    "Does the evidence suggest the presence of elevated amyloid burden in the brain in this patient?",
    "Is there a high likelihood of underlying amyloid pathology in the brain based on the patient's profile?"
]


# Raw answer texts
PET_OPTION_TEXTS = ["Yes", "No"]

# Map AMYLPET value to answer text
PET_ANSWER_MAP = {
    1: "Yes",  # Amyloid positive
    0: "No",   # Amyloid negative
}

def add_pet_question(row, *, seed=None):
    rng = random.Random(seed if seed is not None else row.name)

    # 1️⃣ Choose a question variant randomly
    row['question'] = rng.choice(pet_question_variants)

    # 2️⃣ Remove sensitive fields from the summary
    # json_file = json.loads(row['patient_summary'])
    # for key in pet_keys_remove:
    #     if key in json_file.get('Imaging evidence', {}):
    #         json_file['Imaging evidence'].pop(key)
    #     if key in json_file.get('CSF evidence', {}):
    #         json_file['CSF evidence'].pop(key)
    # row['patient_summary'] = json.dumps(json_file, indent=4)

    # 3️⃣ Shuffle the answer options
    shuffled = PET_OPTION_TEXTS.copy()
    rng.shuffle(shuffled)
    letters = list(string.ascii_uppercase[:len(shuffled)])
    row["options"] = "\n".join(f"{ltr}. {opt}" for ltr, opt in zip(letters, shuffled))

    # 4️⃣ Determine correct letter based on AMYLPET value
    correct_text = PET_ANSWER_MAP[row['AMYLOID_PET_POSITIVE']]
    correct_letter = letters[shuffled.index(correct_text)]
    row["ground_truth"] = correct_letter
    
    row['ground_truth_text'] = correct_text

    return row

In [22]:
# Apply the function to the MCI training set
test_pet = test.apply(add_pet_question, axis=1)

In [23]:
test_pet['ground_truth_text'].value_counts()

ground_truth_text
No     715
Yes    677
Name: count, dtype: int64

In [24]:
test_pet["ID"] = test_pet["RID"]
test_pet = test_pet[columns]
print(len(test_pet))
test_pet = test_pet.dropna(how='any').reset_index(drop=True)
print(len(test_pet))

1392
1392

/scratch/ipykernel_225100/2769316785.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_pet["ID"] = test_pet["RID"]

In [25]:
test_pet['Q_TYPE'] = "Amyloid PET"

In [26]:
test_pet.head()

,ID,patient_summary,diag_summary,visit_summary,question,options,ground_truth,ground_truth_text,COHORT,Q_TYPE
0,6234,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...","The subject is a 70.6-year-old White, female p...",Does the evidence suggest the presence of elev...,A. Yes\nB. No,B,No,ADNI,Amyloid PET
1,2308,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",The subject is a 74.88-year-old male participa...,Does the patient likely have abnormal amyloid ...,A. No\nB. Yes,A,No,ADNI,Amyloid PET
2,7042,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",The subject is a 61.73-year-old Black or Afric...,Is the patient likely to have elevated amyloid...,A. No\nB. Yes,A,No,ADNI,Amyloid PET
3,6147,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",The subject is a 69.7-year-old male born in Ju...,Does the patient likely have abnormal amyloid ...,A. No\nB. Yes,B,Yes,ADNI,Amyloid PET
4,4444,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",The patient is a 77.7-year-old male born in Ju...,Does the patient likely have abnormal amyloid ...,A. Yes\nB. No,A,Yes,ADNI,Amyloid PET

In [27]:
test_pet.to_csv(f"{directory_path}/training_data/testing_data_grpo/with_summary/test_pet.csv", index=False)

# Add primary etiology question

In [28]:
test['DIAGNOSIS'].value_counts()

DIAGNOSIS
2.0    603
1.0    555
3.0    234
Name: count, dtype: int64

In [29]:
def add_ad_label(row):
    if (row['DIAGNOSIS'] in [2.0, 3.0]) & (row['AMYLOID_PET_POSITIVE'] == 1):
        return 'AD'
    elif row['DIAGNOSIS'] == 1.0:
        return 'NC'

test['AD_LABEL'] = test.apply(add_ad_label, axis=1)
test['AD_LABEL'].value_counts()

AD_LABEL
NC    555
AD    504
Name: count, dtype: int64

In [30]:
test[test['AD_LABEL'].isna()]['AMYLOID_PET_POSITIVE'].value_counts()

AMYLOID_PET_POSITIVE
0    333
Name: count, dtype: int64

In [31]:
import random, string

etiology_question_variants = [
    "Identify the primary etiologic diagnosis of the patient using the information provided, if applicable.",
    "Identify the primary etiology of the patient's cognitive impairment using the information provided, if applicable.",
    "Based on the clinical details, determine the main cause of the patient's cognitive impairment, if applicable.",
    "Using the information provided, identify the primary cause of the patient's cognitive decline, if applicable.",
    "Determine the primary etiology underlying the patient's cognitive impairment based on the provided information, if applicable."
]

# Raw etiology answer texts in original order
ETIOLOGY_OPTION_TEXTS = [
    "Alzheimer's disease (AD)",
    "Lewy body disease (LBD)",
    "Frontotemporal lobar degeneration and its variants, including primary progressive aphasia, corticobasal degeneration and progressive supranuclear palsy, and with or without amyotrophic lateral sclerosis (FTLD)",
    "Vascular brain injury or vascular dementia including stroke (VD)",
    "Systemic and environmental factors including infectious diseases (HIV included), metabolic, substance abuse / alcohol, medications, systemic disease and delirium (SEF)",
    "Psychiatric conditions including schizophrenia, depression, bipolar disorder, anxiety and posttraumatic stress disorder (PSY)",
    "Other (Multiple system atrophy, Essential tremor, Down syndrome, Huntington's disease, Prion disease, Traumatic brain injury, Normal-pressure hydrocephalus, Epilepsy, CNS neoplasm, etc)",
    "Not applicable (no cognitive impairment)",
]

# Mapping of ETPR code to correct answer text
ETPR_ANSWER_MAP = {
    'AD': ETIOLOGY_OPTION_TEXTS[0],
    'NC': ETIOLOGY_OPTION_TEXTS[-1],
}

def add_etpr_question(row, *, seed=None):
    rng = random.Random(seed if seed is not None else row.name)

    # 1️⃣ Randomly select a question variant
    row['question'] = rng.choice(etiology_question_variants)

    # 2️⃣ Shuffle options and assign fresh letters
    shuffled = ETIOLOGY_OPTION_TEXTS.copy()
    rng.shuffle(shuffled)
    letters = list(string.ascii_uppercase[:len(shuffled)])
    row['options'] = "\n".join(f"{ltr}. {opt}" for ltr, opt in zip(letters, shuffled))

    # 3️⃣ Get correct text from ETPR code (default to "Not applicable" if unknown)
    correct_text = ETPR_ANSWER_MAP.get(row['AD_LABEL'])

    if correct_text is None:
        raise ValueError(f"Invalid ETPR value: {row['AD_LABEL']}")


    # 4️⃣ Get ground truth letter from shuffled list
    if correct_text in shuffled:
        row['ground_truth'] = letters[shuffled.index(correct_text)]
    else:
        row['ground_truth'] = None  # shouldn't happen unless text mismatch
        
    row['ground_truth_text'] = correct_text

    return row

In [32]:
# Apply the function to the MCI training set
test_etpr = test[~test['AD_LABEL'].isna()]
test_etpr = test_etpr.apply(add_etpr_question, axis=1)

In [33]:
test_etpr['ground_truth_text'].value_counts()

ground_truth_text
Not applicable (no cognitive impairment)    555
Alzheimer's disease (AD)                    504
Name: count, dtype: int64

In [34]:
test_etpr["ID"] = test_etpr["RID"]
test_etpr = test_etpr[columns]
print(len(test_etpr))
test_etpr = test_etpr.dropna(how='any').reset_index(drop=True)
print(len(test_etpr))

1059
1059

/scratch/ipykernel_225100/3397397685.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_etpr["ID"] = test_etpr["RID"]

In [35]:
test_etpr['Q_TYPE'] = "Primary etiology"

In [36]:
test_etpr.head()

,ID,patient_summary,diag_summary,visit_summary,question,options,ground_truth,ground_truth_text,COHORT,Q_TYPE
0,6234,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...","The subject is a 70.6-year-old White, female p...","Using the information provided, identify the p...",A. Not applicable (no cognitive impairment)\nB...,A,Not applicable (no cognitive impairment),ADNI,Primary etiology
1,7042,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",The subject is a 61.73-year-old Black or Afric...,Identify the primary etiologic diagnosis of th...,A. Vascular brain injury or vascular dementia ...,E,Not applicable (no cognitive impairment),ADNI,Primary etiology
2,6147,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",The subject is a 69.7-year-old male born in Ju...,Identify the primary etiology of the patient's...,A. Lewy body disease (LBD)\nB. Psychiatric con...,G,Not applicable (no cognitive impairment),ADNI,Primary etiology
3,4444,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...",The patient is a 77.7-year-old male born in Ju...,Identify the primary etiology of the patient's...,A. Lewy body disease (LBD)\nB. Frontotemporal ...,G,Alzheimer's disease (AD),ADNI,Primary etiology
4,6488,"{""Subject Demographics"": {""1. Participant Gend...","{""Which best describes the participant's curre...","The subject is a 76.6-year-old White, non-Hisp...",Determine the primary etiology underlying the ...,"A. Other (Multiple system atrophy, Essential t...",E,Not applicable (no cognitive impairment),ADNI,Primary etiology

In [37]:
test_etpr.to_csv(f"{directory_path}/training_data/testing_data_grpo/with_summary/test_etpr.csv", index=False)