## Prepare questions from NACC for testing GRPO model

Created by: Sahana Kowshik

Date: 05/09/2025

In [1]:
import pandas as pd
import json
import random
import numpy as np
import string

In [2]:
directory_path = "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc"

# Load the datasets

In [3]:
with open(f"{directory_path}/training_data/id_to_hashid_train.pkl", "rb") as f:
    id_to_hashid_train = pd.read_pickle(f)
    
    
hashid_to_id_train = {v:k for k, v in id_to_hashid_train.items()}

### Load the previous test file

In [4]:
old_test = pd.read_csv(f"{directory_path}/training_data/testing_data_grpo_old/test_summary.csv")

/scratch/ipykernel_1703046/1834513179.py:1: DtypeWarning: Columns (20,22,24,28,43,45,50,93,94,95,96,97,98,99,100,101,102,103,104,105,164,175,178,216,219,221,223,225,227,229,231,233,235,237,239,241,243,245,398,400,420,422,431,444,453,571,599,607,663,679,696,699,716,727,733,808,825,949,957,958,959,960,998,1017,1022,1192,1196,1199,1395,1397,1399,1400,1402,1409,1411,1413,1414,1421,1423,1425,1427,1428,1435,1450,1464,1478,1492,1494,1530,1546,1548,1550,1552,1554,1556,1558,1560,1562,1564,1566,1568,1570,1572,1574,1576,1578,1580,1582,1584,1586,1588,1590,1592,1594,1596,1598,1600,1650,1651,1653,1654,1657,1658,1661,1662,1665,1666,1669,1670,1744,1803,1812,1814,1816,1818,1829,1831,1833,1841,1843,1845,1847,1855,1857,1859,1861,1887) have mixed types. Specify dtype option on import or set low_memory=False.
  old_test = pd.read_csv(f"{directory_path}/training_data/testing_data_grpo_old/test_summary.csv")

In [6]:
print(len(old_test))
old_test.head()

5812

,NACCID,NACCVNUM,NACCADC,PACKET,FORMVER,VISITMO,VISITDAY,VISITYR,NACCAVST,NACCNVST,...,RTRTEMM,NACCDICO,sort_key,sort_year,patient_summary,diag_summary,VISITGAP,visit_summary_prompt,visit_summary,COHORT
0,NACC772223,1,5310,I,2.0,1,29,2009,1,1,...,NaN,NaN,0,NaN,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",1,<|im_start|>user\nYou will receive patient dat...,"The subject is a 78-year-old White, right-hand...",NACC
1,NACC900564,5,8974,F,2.0,12,2,2009,5,5,...,NaN,NaN,0,NaN,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",2,<|im_start|>user\nYou will receive patient dat...,"The subject is an 89-year-old right-handed, En...",NACC
2,NACC586854,4,8658,T,3.0,8,23,2016,4,2,...,NaN,NaN,0,NaN,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",0,<|im_start|>user\nYou will receive patient dat...,The subject is a 63-year-old female who visite...,NACC
3,NACC474857,3,2096,F,2.0,3,23,2010,3,3,...,NaN,NaN,0,NaN,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",2,<|im_start|>user\nYou will receive patient dat...,The subject is a 67-year-old male of White rac...,NACC
4,NACC316274,9,5783,F,2.0,10,1,2014,9,9,...,NaN,NaN,0,NaN,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",1,<|im_start|>user\nYou will receive patient dat...,"The subject is a 103-year-old right-handed, En...",NACC

### Load NACC train and the file with summaries and merge them

In [7]:
all_nacc_train = pd.read_csv(f"{directory_path}/train.csv")
all_nacc_train_summary = pd.read_csv(f"{directory_path}/training_data/training_data_grpo_modified_cog_np/train_summary.csv")

/scratch/ipykernel_1703046/2221594878.py:1: DtypeWarning: Columns (20,22,24,26,28,40,43,45,47,50,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,164,175,178,188,216,219,221,223,225,227,229,231,233,235,237,239,241,243,245,247,249,251,253,255,257,259,261,263,265,267,269,271,396,398,400,420,422,431,444,453,492,571,599,607,679,693,696,699,716,727,733,808,819,823,825,831,892,947,948,949,957,958,959,960,1017,1022,1192,1196,1199,1395,1397,1399,1400,1402,1409,1411,1413,1414,1421,1423,1425,1427,1428,1435,1450,1464,1478,1492,1494,1530,1546,1548,1550,1552,1554,1556,1558,1560,1562,1564,1566,1568,1570,1572,1574,1576,1578,1580,1582,1584,1586,1588,1590,1592,1594,1596,1598,1600,1650,1651,1653,1654,1657,1658,1661,1662,1665,1666,1669,1670,1744,1803,1812,1814,1816,1818,1829,1831,1833,1841,1843,1845,1847,1855,1857,1859,1861,1887) have mixed types. Specify dtype option on import or set low_memory=False.
  all_nacc_train = pd.read_csv(f"{directory_path}/train.csv")

In [10]:
all_nacc_train_summary_sub = all_nacc_train_summary[['ID', 'visit_summary', 'visit_summary_prompt']]
all_nacc_train_summary_sub.head()

,ID,visit_summary,visit_summary_prompt
0,NACC814828,"The subject is an 83-year-old right-handed, En...",<|im_start|>user\nYou will receive patient dat...
1,NACC142849,The subject is an 80-year-old male who present...,<|im_start|>user\nYou will receive patient dat...
2,NACC698306,The patient is an 81-year-old White female who...,<|im_start|>user\nYou will receive patient dat...
3,NACC517465,The subject is a 61-year-old right-handed male...,<|im_start|>user\nYou will receive patient dat...
4,NACC215680,The subject is a 72-year-old male of Puerto Ri...,<|im_start|>user\nYou will receive patient dat...

In [11]:
all_nacc_train_merged = pd.merge(all_nacc_train, all_nacc_train_summary_sub, left_on="NACCID", right_on="ID")
all_nacc_train_merged.drop(['ID'], axis=1, inplace=True)

In [12]:
print("all_nacc_train.csv:", len(all_nacc_train))
print("train_summary.csv:", len(all_nacc_train_summary))
print("all_nacc_train_merged.csv:", len(all_nacc_train_merged))

all_nacc_train.csv: 43064
train_summary.csv: 43064
all_nacc_train_merged.csv: 43064

In [13]:
all_nacc_train_merged.head()

,NACCID,NACCVNUM,NACCADC,PACKET,FORMVER,VISITMO,VISITDAY,VISITYR,NACCAVST,NACCNVST,...,RTRTEMM,NACCDICO,sort_key,sort_year,patient_summary,diag_summary,VISITGAP,COHORT,visit_summary,visit_summary_prompt
0,NACC367823,1,2289,I,2.0,9,2,2009,1,1,...,NaN,NaN,0,NaN,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",NaN,NACC,The subject is a 70-year-old right-handed Whit...,<|im_start|>user\nYou will receive patient dat...
1,NACC015497,8,6499,F,3.0,2,28,2023,8,6,...,NaN,NaN,0,NaN,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",NaN,NACC,"The subject is a 70-year-old right-handed, Whi...",<|im_start|>user\nYou will receive patient dat...
2,NACC391642,5,4032,T,3.2,2,7,2022,5,2,...,NaN,NaN,0,NaN,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",NaN,NACC,The subject is a 77-year-old female who is rig...,<|im_start|>user\nYou will receive patient dat...
3,NACC336399,1,4935,I,3.0,4,19,2017,1,1,...,NaN,NaN,0,NaN,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",NaN,NACC,The subject is a 61-year-old female of White r...,<|im_start|>user\nYou will receive patient dat...
4,NACC915222,4,8354,F,3.0,11,4,2022,4,4,...,NaN,NaN,0,NaN,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",NaN,NACC,The subject is a 73-year-old male who presente...,<|im_start|>user\nYou will receive patient dat...

### Load the oversampling dataset used for training

In [14]:
train_oversample_subset = pd.read_csv(f"{directory_path}/training_data/training_data_grpo_modified_cog_np_HASH/subset/all_train_inc_oversample_sub.csv")
# Map the 'ID' column in all_nacc_train and train_oversample_subset to their hashid using id_to_hashid_train
train_oversample_subset['hashid'] = train_oversample_subset['ID']
train_oversample_subset['ID'] = train_oversample_subset['hashid'].map(hashid_to_id_train)

In [16]:
print("train_oversample_subset.csv:", len(train_oversample_subset))
print("train_oversample_subset.csv unique ID:", len(train_oversample_subset['ID'].unique()))

train_oversample_subset.csv: 23864
train_oversample_subset.csv unique ID: 17847

In [17]:
len(set(all_nacc_train_merged['NACCID']).intersection(set(train_oversample_subset['ID'])))

17847

### Find the remaining cases in the train set after removing the cases used for training and merge them with the test set

In [19]:
remaining_train_cases = all_nacc_train_merged[~all_nacc_train_merged['NACCID'].isin(train_oversample_subset['ID'])].reset_index(drop=True)

In [21]:
test = pd.concat([old_test, remaining_train_cases], axis=0).sample(frac=1, random_state=42).reset_index(drop=True)

In [24]:
print("remaining_train_cases.csv:", len(remaining_train_cases))
print("test:", len(test))

remaining_train_cases.csv: 25217
test: 31029

In [25]:
test.head()

,NACCID,NACCVNUM,NACCADC,PACKET,FORMVER,VISITMO,VISITDAY,VISITYR,NACCAVST,NACCNVST,...,RTRTEMM,NACCDICO,sort_key,sort_year,patient_summary,diag_summary,VISITGAP,visit_summary_prompt,visit_summary,COHORT
0,NACC282885,1,8354,I,3.0,6,26,2018,1,1,...,8.8888,1.0,1,0.0,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",NaN,<|im_start|>user\nYou will receive patient dat...,The subject is an 83-year-old right-handed mal...,NACC
1,NACC837281,7,4967,F,2.0,1,10,2013,7,7,...,NaN,NaN,0,NaN,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",NaN,<|im_start|>user\nYou will receive patient dat...,"The subject is a 64-year-old right-handed, Whi...",NACC
2,NACC355961,1,8354,I,3.0,3,1,2017,1,1,...,8.8888,1.0,1,0.0,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",NaN,<|im_start|>user\nYou will receive patient dat...,"The subject is a 77-year-old right-handed, Eng...",NACC
3,NACC385116,1,4967,I,1.0,11,1,2005,1,1,...,NaN,NaN,0,NaN,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",NaN,<|im_start|>user\nYou will receive patient dat...,The patient is a 57-year-old White female who ...,NACC
4,NACC260495,2,9637,F,1.0,3,20,2007,2,2,...,NaN,NaN,0,NaN,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Indicate ...",0.0,<|im_start|>user\nYou will receive patient dat...,The subject is a 70-year-old male of White rac...,NACC

In [26]:
set(test['NACCID']).intersection(set(train_oversample_subset['ID']))

set()

In [27]:
test.to_csv(f"{directory_path}/training_data/testing_data_grpo/test_summary.csv", index=False)

In [30]:
assert len(test) == len(test['NACCID'].unique())

# Create test datasets

In [31]:
# Add ETPR variables
def add_etpr_labels(row):
    value = row['NACCETPR']
    
    # NC
    if value == 88:
        row['ETPR'] = 'NC'
    
    # AD
    elif value == 1:
        row['ETPR'] = 'AD'

    # LBD
    elif value == 2:
        row['ETPR'] = 'LBD'

    # VD
    elif value == 8:
        row['ETPR'] = 'VD'

    # FTLD and its variants, including CBD and PSP, with or without ALS
    elif value in [4, 5, 6, 7]:
        row['ETPR'] = 'FTLD'
    
    # SEF: seizure, epilepsy, etc.
    elif value in [17, 18, 23, 26, 27, 28, 29]:
        row['ETPR'] = 'SEF'

    # Psychiatric conditions
    elif value in [19, 20, 21, 22, 24, 25]:
        row['ETPR'] = 'PSY'

    # Other degenerative
    elif value not in [30, 88, 99]:
        row['ETPR'] = 'ODE'

    else:
        row['ETPR'] = np.NaN

    return row


test = test.apply(add_etpr_labels, axis=1)

In [32]:
len(test[~test['ETPR'].isna()])

29788

In [33]:
sum(dict(test['ETPR'].value_counts()).values())

29788

In [34]:
test['ETPR'].value_counts()

ETPR
NC      13819
AD      13099
FTLD     1258
LBD       595
VD        403
SEF       240
PSY       205
ODE       169
Name: count, dtype: int64

In [35]:
# Function to add NP ground truth columns
def add_mci_ground_truth(row):
    # Alzheimer's Disease
    if row['NACCTMCI'] in [1, 2]:
        row['MCI'] = 0
    elif row['NACCTMCI'] in [3, 4]:
        row['MCI'] = 1
    elif row['NACCTMCI'] in [8]:
        row['MCI'] = 2

    return row

# Apply the function across the training set
test = test.apply(add_mci_ground_truth, axis=1)

In [36]:
test['MCI'].value_counts()

MCI
2    26360
0     3550
1     1119
Name: count, dtype: int64

In [37]:
test['ID'] = test['NACCID']
test.drop(['NACCID'], axis=1, inplace=True)

/scratch/ipykernel_1703046/3636380100.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test['ID'] = test['NACCID']

In [38]:
columns = ['ID', 'patient_summary', 'diag_summary', 'visit_summary', 'visit_summary_prompt',  'question', 'options', 'ground_truth', 'ground_truth_text', 'COHORT']

## Neuropath one and mixed

In [39]:
test_np = test[
    (test['NACCUDSD'] != 1) &
    (test['NACCLEWY'].isin([0, 1, 2, 3, 4])) &
    (
        (test['NPFTDTAU'].isin([0]) & test['NPFTDTDP'].isin([0])) | 
        test['NPFTDTAU'].isin([1]) | 
        test['NPFTDTDP'].isin([1])
    ) &
    (test['NPADNC'].isin([0, 1, 2, 3])) &
    (test['VISITGAP'] <= 3)
].sample(frac=1, random_state=42).reset_index(drop=True)

print(len(test_np))

668

In [40]:
# Function to add NP ground truth columns
def add_ground_truth(row):
    # Alzheimer's Disease
    if row['NPADNC'] in [2, 3]:
        row['NP_AD'] = 1
        row['NP_AVAIL'] = 1
    elif row['NPADNC'] in [0, 1]:
        row['NP_AD'] = 0
        row['NP_AVAIL'] = 1

    # Lewy Body Disease
    if row['NACCLEWY'] in [1, 2, 3, 4]:
        row['NP_LBD'] = 1
        row['NP_AVAIL'] = 1
    elif row['NACCLEWY'] == 0:
        row['NP_LBD'] = 0
        row['NP_AVAIL'] = 1

    # Frontotemporal Degeneration (FTLD-tau or other)
    if (row['NPFTDTAU'] == 1) | (row['NPFTDTDP'] == 1):
        row['NP_FTD'] = 1
        row['NP_AVAIL'] = 1
    elif (row['NPFTDTAU'] == 0) & (row['NPFTDTDP'] == 0):
        row['NP_FTD'] = 0
        row['NP_AVAIL'] = 1

    return row

In [41]:
def split_df(row):
    combo = (row["NP_AD"], row["NP_LBD"], row["NP_FTD"])
    row["one_count"] = sum(combo)
    return row

In [42]:
# Apply the function across the training set
test_np = test_np.apply(add_ground_truth, axis=1)
test_np = test_np.apply(split_df, axis=1)

# Check distribution of available neuropathology labels
test_np['NP_AVAIL'].value_counts()

NP_AVAIL
1    668
Name: count, dtype: int64

In [43]:
test_np['one_count'].value_counts()

one_count
1    313
2    268
0     63
3     24
Name: count, dtype: int64

In [44]:
def add_np_question(row, *, np_question_variants, NP_OPTION_TEXTS, NP_ANSWER_MAP, seed=None):
    """
    Adds three new columns to each row:
    ─ question : one of the phrasing variants           (string)
    ─ options  : the shuffled, letter-prefixed choices  (multiline string)
    ─ ground_truth : the **letter** (A-H) of the correct choice (string)
    """
    rng = random.Random(seed if seed is not None else row.name)  # reproducible per-row if you like

    # 1️⃣ Choose a question at random
    row["question"] = rng.choice(np_question_variants)

    # 2️⃣ Shuffle the options and assign fresh letters
    shuffled = NP_OPTION_TEXTS.copy()
    rng.shuffle(shuffled)
    letters = list(string.ascii_uppercase[: len(shuffled)])
    row["options"] = "\n".join(f"{ltr}. {opt}" for ltr, opt in zip(letters, shuffled))

    # 3️⃣ Work out which *text* is correct for this patient
    combo = (row["NP_AD"], row["NP_LBD"], row["NP_FTD"])
    correct_text = NP_ANSWER_MAP[combo]

    # 4️⃣ Convert that to the new letter after shuffling
    correct_letter = letters[shuffled.index(correct_text)]
    row["ground_truth"] = correct_letter
    
    row['ground_truth_text'] = correct_text

    return row

In [45]:
np_question_variants_one = [
    "Which of the following pathology is causing the patient's cognitive impairment based on the clinical information provided?",
    "Using the provided clinical information, determine the pathological cause of the patient's cognitive decline from the options listed below.",
    "Based on the clinical data, identify the neuropathology responsible for the patient's cognitive impairment by selecting from the given choices.",
    "From the options below, select the disease pathology causing cognitive impairment as indicated by the clinical information.",
    "Review the provided clinical information and choose the pathology underlying the patient's cognitive symptoms from the available options."
]

# Pull the bare answer texts into a list – easier to shuffle
NP_OPTION_TEXTS_ONE = [
    "Alzheimer's disease pathology (AD)",
    "Lewy body pathology (LBD)",
    "Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    "No listed option is correct",
]

NP_ANSWER_MAP_ONE = {
    (0, 0, 1): "Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    (0, 1, 0): "Lewy body pathology (LBD)",
    (1, 0, 0): "Alzheimer's disease pathology (AD)",
    (0, 0, 0): "No listed option is correct",
}

test_np_one = test_np[test_np['one_count'] <= 1].reset_index(drop=True)
# Apply question and label assignment
test_np_one = test_np_one.apply(add_np_question, np_question_variants=np_question_variants_one, NP_OPTION_TEXTS=NP_OPTION_TEXTS_ONE, NP_ANSWER_MAP=NP_ANSWER_MAP_ONE, axis=1)

In [46]:
# Select final columns to keep
test_np_one = test_np_one[columns]  # Make sure 'columns' is defined somewhere earlier
test_np_one['Q_TYPE'] = 'Neuropath'
test_np_one.to_csv(f"{directory_path}/training_data/testing_data_grpo/with_summary/test_np_one.csv", index=False)

In [47]:
np_question_variants_mixed = [
    "Which of the following pathologies are causing the patient's cognitive impairment based on the clinical information provided?",
    "Using the provided clinical information, determine the pathological causes of the patient's cognitive decline from the options listed below.",
    "Based on the clinical data, identify the neuropathologies responsible for the patient's cognitive impairment by selecting from the given choices.",
    "From the options below, select the disease pathologies causing cognitive impairment as indicated by the clinical information.",
    "Review the provided clinical information and choose the pathologies underlying the patient's cognitive symptoms from the available options."
]

NP_OPTION_TEXTS_MIXED = [
    "Alzheimer's disease pathology (AD) and Lewy body pathology (LBD)",
    "Alzheimer's disease pathology (AD) and Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    "Lewy body pathology (LBD) and Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    "Alzheimer's disease pathology (AD), Lewy body pathology (LBD) and Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    "No listed option is correct",
]

NP_ANSWER_MIXED = {
    (1, 1, 1): "Alzheimer's disease pathology (AD), Lewy body pathology (LBD) and Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    (0, 1, 1): "Lewy body pathology (LBD) and Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    (1, 0, 1): "Alzheimer's disease pathology (AD) and Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    (1, 1, 0): "Alzheimer's disease pathology (AD) and Lewy body pathology (LBD)",
    (0, 0, 0): "No listed option is correct",
}

test_np_mixed = test_np[test_np['one_count'].isin([0,2,3])].reset_index(drop=True)
# Apply question and label assignment
test_np_mixed = test_np_mixed.apply(add_np_question, np_question_variants=np_question_variants_mixed, NP_OPTION_TEXTS=NP_OPTION_TEXTS_MIXED, NP_ANSWER_MAP=NP_ANSWER_MIXED, axis=1)

In [48]:
# Select final columns to keep
test_np_mixed = test_np_mixed[columns]  # Make sure 'columns' is defined somewhere earlier
test_np_mixed['Q_TYPE'] = 'Neuropath'
test_np_mixed.to_csv(f"{directory_path}/training_data/testing_data_grpo/with_summary/test_np_mixed.csv", index=False)

In [49]:
len(set(test_np_one['ID']).intersection(set(test_np_mixed['ID'])))

63

## Neuropathology

In [50]:
# test_np = test[((test['NACCLEWY'].isin([0,1,2,3,4])) & (test['NPFTDTAU'].isin([0,1])) & (test['NPADNC'].isin([0,1,2,3])))].sample(frac=1, random_state=0).reset_index(drop=True)

In [51]:
test_np = test[
    (test['NACCUDSD'] != 1) &
    (test['NACCLEWY'].isin([0, 1, 2, 3, 4])) &
    (
        (test['NPFTDTAU'].isin([0]) & test['NPFTDTDP'].isin([0])) | 
        test['NPFTDTAU'].isin([1]) | 
        test['NPFTDTDP'].isin([1])
    ) &
    (test['NPADNC'].isin([0, 1, 2, 3])) &
    (test['VISITGAP'] <= 3)
].sample(frac=1, random_state=42).reset_index(drop=True)

print(len(test_np))

668

In [52]:
# Function to add NP ground truth columns
def add_ground_truth(row):
    # Alzheimer's Disease
    if row['NPADNC'] in [2, 3]:
        row['NP_AD'] = 1
        row['NP_AVAIL'] = 1
    elif row['NPADNC'] in [0, 1]:
        row['NP_AD'] = 0
        row['NP_AVAIL'] = 1

    # Lewy Body Disease
    if row['NACCLEWY'] in [1, 2, 3, 4]:
        row['NP_LBD'] = 1
        row['NP_AVAIL'] = 1
    elif row['NACCLEWY'] == 0:
        row['NP_LBD'] = 0
        row['NP_AVAIL'] = 1

    # Frontotemporal Degeneration (FTLD-tau or other)
    if (row['NPFTDTAU'] == 1) | (row['NPFTDTDP'] == 1):
        row['NP_FTD'] = 1
        row['NP_AVAIL'] = 1
    elif (row['NPFTDTAU'] == 0) & (row['NPFTDTDP'] == 0):
        row['NP_FTD'] = 0
        row['NP_AVAIL'] = 1

    return row

In [53]:
# Apply the function across the training set
test_np = test_np.apply(add_ground_truth, axis=1)

# Check distribution of available neuropathology labels
test_np['NP_AVAIL'].value_counts()

NP_AVAIL
1    668
Name: count, dtype: int64

In [54]:
import random, string
import pandas as pd

# Neuropathology Question Variants
np_question_variants = [
    "Which of the following pathologies are causing the patient's cognitive impairment based on the clinical information provided?",
    "Using the provided clinical information, determine the pathological causes of the patient's cognitive decline from the options listed below.",
    "Based on the clinical data, identify the neuropathologies responsible for the patient's cognitive impairment by selecting from the given choices.",
    "From the options below, select the disease pathologies causing cognitive impairment as indicated by the clinical information.",
    "Review the provided clinical information and choose the pathologies underlying the patient's cognitive symptoms from the available options."
]

# Pull the bare answer texts into a list – easier to shuffle
NP_OPTION_TEXTS = [
    "Alzheimer's disease pathology (AD) only",
    "Lewy body pathology (LBD) only",
    "Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD) only",
    "Alzheimer's disease pathology (AD) and Lewy body pathology (LBD)",
    "Alzheimer's disease pathology (AD) and Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    "Lewy body pathology (LBD) and Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    "Alzheimer's disease pathology (AD), Lewy body pathology (LBD) and Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    "No listed option is correct",
]

# map each neuropathology pattern → the **text** of the correct option
NP_ANSWER_MAP = {
    (1, 1, 1): "Alzheimer's disease pathology (AD), Lewy body pathology (LBD) and Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    (0, 1, 1): "Lewy body pathology (LBD) and Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    (1, 0, 1): "Alzheimer's disease pathology (AD) and Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD)",
    (1, 1, 0): "Alzheimer's disease pathology (AD) and Lewy body pathology (LBD)",
    (0, 0, 1): "Frontotemporal Lobar Degeneration with tau pathology or TDP-43 pathology (FTLD) only",
    (0, 1, 0): "Lewy body pathology (LBD) only",
    (1, 0, 0): "Alzheimer's disease pathology (AD) only",
    (0, 0, 0): "No listed option is correct",
}


def add_np_question(row, *, seed=None):
    """
    Adds three new columns to each row:
    ─ question : one of the phrasing variants           (string)
    ─ options  : the shuffled, letter-prefixed choices  (multiline string)
    ─ ground_truth : the **letter** (A-H) of the correct choice (string)
    """
    rng = random.Random(seed if seed is not None else row.name)  # reproducible per-row if you like

    # 1️⃣ Choose a question at random
    row["question"] = rng.choice(np_question_variants)

    # 2️⃣ Shuffle the options and assign fresh letters
    shuffled = NP_OPTION_TEXTS.copy()
    rng.shuffle(shuffled)
    letters = list(string.ascii_uppercase[: len(shuffled)])
    row["options"] = "\n".join(f"{ltr}. {opt}" for ltr, opt in zip(letters, shuffled))

    # 3️⃣ Work out which *text* is correct for this patient
    combo = (row["NP_AD"], row["NP_LBD"], row["NP_FTD"])
    correct_text = NP_ANSWER_MAP[combo]

    # 4️⃣ Convert that to the new letter after shuffling
    correct_letter = letters[shuffled.index(correct_text)]
    row["ground_truth"] = correct_letter
    
    row['ground_truth_text'] = correct_text

    return row

In [55]:
# Apply question and label assignment
test_np = test_np.apply(add_np_question, axis=1)

# Check ground truth distribution
test_np['ground_truth'].value_counts()

ground_truth
E    92
A    90
H    89
D    86
C    82
G    80
B    80
F    69
Name: count, dtype: int64

In [56]:
# Update set of NACCIDs used to avoid duplication later
np_ids = set(test_np['ID'])

# Optional: Check distribution of diagnosis codes
test_np['NACCUDSD'].value_counts()

NACCUDSD
4    581
3     87
Name: count, dtype: int64

In [57]:
# Select final columns to keep
test_np = test_np[columns]  # Make sure 'columns' is defined somewhere earlier
test_np['Q_TYPE'] = 'Neuropath'

In [58]:
test_np.to_csv(f"{directory_path}/training_data/testing_data_grpo/with_summary/test_np.csv", index=False)

## NACCTMCI

In [59]:
test['MCI'].value_counts()

MCI
2    26360
0     3550
1     1119
Name: count, dtype: int64

In [60]:
# Sample MCI patients, excluding those already selected for NP, PET, or DAT tasks
test_mci = (
    test
    .groupby('MCI', group_keys=False)
    .apply(lambda x: x.sample(n=min(len(x), 3550), random_state=42))  # Safe sampling
    .sample(frac=1, random_state=42)  # Shuffle the sampled rows
    .reset_index(drop=True)
)

# Check the number of sampled patients per MCI subtype
test_mci['MCI'].value_counts()

/scratch/ipykernel_1703046/2671262082.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(n=min(len(x), 3550), random_state=42))  # Safe sampling

MCI
2    3550
0    3550
1    1119
Name: count, dtype: int64

In [61]:
test_mci['NACCUDSD'].value_counts()

NACCUDSD
3    4669
1    1911
4    1639
Name: count, dtype: int64

In [62]:
import random, string

# Question variants for MCI subtype classification
mci_question_variants = [
    "Determine, if applicable, the correct subtype of mild cognitive impairment (MCI) for this patient based on the provided information.",
    "Based on the patient's data, identify the appropriate mild cognitive impairment (MCI) subtype, if applicable.",
    "Using the information given, classify the patient's mild cognitive impairment (MCI) subtype, if applicable.",
    "If applicable, identify the subtype of mild cognitive impairment based on the provided patient details.",
    "Analyze the patient's information to identify the correct mild cognitive impairment (MCI) subtype, if applicable."
]


# MCI subtype answer options (original order)
MCI_OPTION_TEXTS = [
    "Amnestic MCI",
    "Non-amnestic MCI",
    "Not applicable (no diagnosis of MCI)",
]

# Mapping NACCTMCI code → correct answer text
MCI_ANSWER_MAP = {
    0: "Amnestic MCI",
    1: "Non-amnestic MCI",
    2: "Not applicable (no diagnosis of MCI)",
}

def add_mci_question(row, *, seed=None):
    rng = random.Random(seed if seed is not None else row.name)

    # 1️⃣ Randomly choose a question phrasing
    row['question'] = rng.choice(mci_question_variants)

    # 2️⃣ Shuffle the answer texts and assign letters
    shuffled = MCI_OPTION_TEXTS.copy()
    rng.shuffle(shuffled)
    letters = list(string.ascii_uppercase[:len(shuffled)])
    row['options'] = "\n".join(f"{ltr}. {opt}" for ltr, opt in zip(letters, shuffled))

    # 3️⃣ Get the correct text for this patient's subtype
    correct_text = MCI_ANSWER_MAP.get(row['MCI'], None)

    # 4️⃣ Assign ground truth letter if valid
    if correct_text in shuffled:
        correct_letter = letters[shuffled.index(correct_text)]
        row['ground_truth'] = correct_letter
    else:
        row['ground_truth'] = None  # in case NACCTMCI is missing or invalid
        
    row['ground_truth_text'] = correct_text

    return row

In [63]:
# Apply the function to the MCI training set
test_mci = test_mci.apply(add_mci_question, axis=1)

In [64]:
# Quick checks
print(test_mci['ground_truth'].value_counts())
print(test_mci['ground_truth_text'].value_counts())
print(test_mci['question'].value_counts())
print(test_mci['NACCUDSD'].value_counts())

ground_truth
C    2850
B    2698
A    2671
Name: count, dtype: int64
ground_truth_text
Not applicable (no diagnosis of MCI)    3550
Amnestic MCI                            3550
Non-amnestic MCI                        1119
Name: count, dtype: int64
question
Determine, if applicable, the correct subtype of mild cognitive impairment (MCI) for this patient based on the provided information.    1686
Analyze the patient's information to identify the correct mild cognitive impairment (MCI) subtype, if applicable.                       1681
If applicable, identify the subtype of mild cognitive impairment based on the provided patient details.                                 1642
Based on the patient's data, identify the appropriate mild cognitive impairment (MCI) subtype, if applicable.                           1637
Using the information given, classify the patient's mild cognitive impairment (MCI) subtype, if applicable.                             1573
Name: count, dtype: int64
NACCUDSD
3    4669
1    1911
4    1639
Name: count, dtype: int64

In [65]:
# Update set of used IDs to avoid reusing these patients elsewhere
mci_ids = set(test_mci['ID'])

In [66]:
# Select only the columns needed for modeling
test_mci = test_mci[columns]
test_mci['Q_TYPE'] = 'MCI subtype'

In [67]:
test_mci.to_csv(f"{directory_path}/training_data/testing_data_grpo/with_summary/test_mci.csv", index=False)

## NACCETPR

In [68]:
# Filter and sample patients for etiology prediction task,
# excluding those already selected for NP, PET, DAT, or MCI tasks
test_etpr = (
    test
    .loc[
        ~(test['ETPR'].isna())  
    ]
    # .groupby('ETPR', group_keys=False)
    # .apply(lambda x: x.sample(n=min(len(x), 1000), random_state=42))  # Sample up to 1000
    .sample(frac=1, random_state=42)  # Shuffle the sampled rows
    .reset_index(drop=True)
)

# Check sampled distribution
test_etpr['ETPR'].value_counts()

ETPR
NC      13819
AD      13099
FTLD     1258
LBD       595
VD        403
SEF       240
PSY       205
ODE       169
Name: count, dtype: int64

In [69]:
import random, string

etiology_question_variants = [
    "Identify the primary etiologic diagnosis of the patient using the information provided, if applicable.",
    "Identify the primary etiology of the patient's cognitive impairment using the information provided, if applicable.",
    "Based on the clinical details, determine the main cause of the patient's cognitive impairment, if applicable.",
    "Using the information provided, identify the primary cause of the patient's cognitive decline, if applicable.",
    "Determine the primary etiology underlying the patient's cognitive impairment based on the provided information, if applicable."
]

# Raw etiology answer texts in original order
ETIOLOGY_OPTION_TEXTS = [
    "Alzheimer's disease (AD)",
    "Lewy body disease (LBD)",
    "Frontotemporal lobar degeneration and its variants, including primary progressive aphasia, corticobasal degeneration and progressive supranuclear palsy, and with or without amyotrophic lateral sclerosis (FTLD)",
    "Vascular brain injury or vascular dementia including stroke (VD)",
    "Systemic and environmental factors including infectious diseases (HIV included), metabolic, substance abuse / alcohol, medications, systemic disease and delirium (SEF)",
    "Psychiatric conditions including schizophrenia, depression, bipolar disorder, anxiety and posttraumatic stress disorder (PSY)",
    "Other (Multiple system atrophy, Essential tremor, Down syndrome, Huntington's disease, Prion disease, Traumatic brain injury, Normal-pressure hydrocephalus, Epilepsy, CNS neoplasm, etc)",
    "Not applicable (no cognitive impairment)",
]

# Mapping of ETPR code to correct answer text
ETPR_ANSWER_MAP = {
    'AD': ETIOLOGY_OPTION_TEXTS[0],
    'LBD': ETIOLOGY_OPTION_TEXTS[1],
    'FTLD': ETIOLOGY_OPTION_TEXTS[2],
    'VD': ETIOLOGY_OPTION_TEXTS[3],
    'SEF': ETIOLOGY_OPTION_TEXTS[4],
    'PSY': ETIOLOGY_OPTION_TEXTS[5],
    'ODE': ETIOLOGY_OPTION_TEXTS[6],
    'NC': ETIOLOGY_OPTION_TEXTS[7],  # fallback/default
}

def add_etpr_question(row, *, seed=None):
    rng = random.Random(seed if seed is not None else row.name)

    # 1️⃣ Randomly select a question variant
    row['question'] = rng.choice(etiology_question_variants)

    # 2️⃣ Shuffle options and assign fresh letters
    shuffled = ETIOLOGY_OPTION_TEXTS.copy()
    rng.shuffle(shuffled)
    letters = list(string.ascii_uppercase[:len(shuffled)])
    row['options'] = "\n".join(f"{ltr}. {opt}" for ltr, opt in zip(letters, shuffled))

    # 3️⃣ Get correct text from ETPR code (default to "Not applicable" if unknown)
    correct_text = ETPR_ANSWER_MAP.get(row['ETPR'])

    if correct_text is None:
        raise ValueError(f"Invalid ETPR value: {row['ETPR']}")


    # 4️⃣ Get ground truth letter from shuffled list
    if correct_text in shuffled:
        row['ground_truth'] = letters[shuffled.index(correct_text)]
    else:
        row['ground_truth'] = None  # shouldn't happen unless text mismatch
        
    row['ground_truth_text'] = correct_text

    return row

In [70]:
# Apply the function to the MCI training set
test_etpr = test_etpr.apply(add_etpr_question, axis=1)

In [71]:
print(test_etpr['ground_truth'].value_counts())
print(test_etpr['ground_truth_text'].value_counts())
print(test_etpr['question'].value_counts())
print(test_etpr['NACCUDSD'].value_counts())

ground_truth
A    3789
D    3768
H    3756
B    3746
E    3725
F    3700
G    3674
C    3630
Name: count, dtype: int64
ground_truth_text
Not applicable (no cognitive impairment)                                                                                                                                                                             13819
Alzheimer's disease (AD)                                                                                                                                                                                             13099
Frontotemporal lobar degeneration and its variants, including primary progressive aphasia, corticobasal degeneration and progressive supranuclear palsy, and with or without amyotrophic lateral sclerosis (FTLD)     1258
Lewy body disease (LBD)                                                                                                                                                                                                595
Vascular brain injury or vascular dementia including stroke (VD)                                                                                                                                                       403
Systemic and environmental factors including infectious diseases (HIV included), metabolic, substance abuse / alcohol, medications, systemic disease and delirium (SEF)                                                240
Psychiatric conditions including schizophrenia, depression, bipolar disorder, anxiety and posttraumatic stress disorder (PSY)                                                                                          205
Other (Multiple system atrophy, Essential tremor, Down syndrome, Huntington's disease, Prion disease, Traumatic brain injury, Normal-pressure hydrocephalus, Epilepsy, CNS neoplasm, etc)                              169
Name: count, dtype: int64
question
Determine the primary etiology underlying the patient's cognitive impairment based on the provided information, if applicable.    6038
Identify the primary etiologic diagnosis of the patient using the information provided, if applicable.                            5999
Using the information provided, identify the primary cause of the patient's cognitive decline, if applicable.                     5966
Identify the primary etiology of the patient's cognitive impairment using the information provided, if applicable.                5938
Based on the clinical details, determine the main cause of the patient's cognitive impairment, if applicable.                     5847
Name: count, dtype: int64
NACCUDSD
1    13819
4    12299
3     3670
Name: count, dtype: int64

In [72]:
# Update set of used IDs to avoid reusing these patients elsewhere
etpr_ids = set(test_etpr['ID'])

In [73]:
# Select only the columns needed for modeling
test_etpr = test_etpr[columns]
test_etpr['Q_TYPE'] = 'Primary etiology'

In [74]:
test_etpr.to_csv(f"{directory_path}/training_data/testing_data_grpo/with_summary/test_etpr.csv", index=False)

In [85]:
assert len(test[test['ETPR'].isna()]) + len(test_etpr) == len(test)

## NACCUDSD

In [75]:
# Filter and sample patients for etiology prediction task,
# excluding those already selected for NP, PET, DAT, or MCI tasks
test_cog = (
    test
    .sample(frac=1, random_state=42)  # Shuffle the sampled rows
    .reset_index(drop=True)
)

# Check sampled distribution
test_cog['NACCUDSD'].value_counts()

NACCUDSD
1    13819
4    12541
3     4669
Name: count, dtype: int64

In [76]:
import random, string

# Question variants for cognitive status identification
cog_question_variants = [
    "Using the information provided, determine the patient's cognitive status.",
    "Identify the patient's cognitive status based on the given information.",
    "Based on the provided clinical details, classify the patient's cognitive status.",
    "From the information available, determine the correct cognitive status for the patient.",
    "Analyze the patient's information and identify their cognitive status."
]

# Original answer texts
COG_OPTION_TEXTS = [
    "Normal Cognition (NC)",
    "Mild Cognitive Impairment (MCI)",
    "Dementia (DE)"
]

# Mapping from NACCUDSD to the correct label text
COG_ANSWER_MAP = {
    1: "Normal Cognition (NC)",
    3: "Mild Cognitive Impairment (MCI)",
    4: "Dementia (DE)",
}

def add_cog_question(row, *, seed=None):
    rng = random.Random(seed if seed is not None else row.name)

    # 1️⃣ Random question phrasing
    row['question'] = rng.choice(cog_question_variants)

    # 2️⃣ Shuffle the answer options
    shuffled = COG_OPTION_TEXTS.copy()
    rng.shuffle(shuffled)
    letters = list(string.ascii_uppercase[:len(shuffled)])
    row['options'] = "\n".join(f"{ltr}. {opt}" for ltr, opt in zip(letters, shuffled))

    # 3️⃣ Determine correct answer letter
    correct_text = COG_ANSWER_MAP.get(row['NACCUDSD'], None)
    if correct_text in shuffled:
        row['ground_truth'] = letters[shuffled.index(correct_text)]
    else:
        row['ground_truth'] = None  # fallback for unrecognized codes
    
    row['ground_truth_text'] = correct_text

    return row

In [77]:
# Apply the function to the MCI training set
test_cog = test_cog.apply(add_cog_question, axis=1)

In [78]:
print(test_cog['ground_truth'].value_counts())
print(test_cog['ground_truth_text'].value_counts())
print(test_cog['question'].value_counts())

ground_truth
B    10384
A    10384
C    10261
Name: count, dtype: int64
ground_truth_text
Normal Cognition (NC)              13819
Dementia (DE)                      12541
Mild Cognitive Impairment (MCI)     4669
Name: count, dtype: int64
question
Analyze the patient's information and identify their cognitive status.                     6300
Using the information provided, determine the patient's cognitive status.                  6241
From the information available, determine the correct cognitive status for the patient.    6212
Identify the patient's cognitive status based on the given information.                    6176
Based on the provided clinical details, classify the patient's cognitive status.           6100
Name: count, dtype: int64

In [79]:
# Update set of used IDs to avoid reusing these patients elsewhere
cog_ids = set(test_cog['ID'])

In [80]:
# Select only the columns needed for modeling
test_cog = test_cog[columns]
test_cog['Q_TYPE'] = 'Cognitive status'

In [81]:
test_cog.to_csv(f"{directory_path}/training_data/testing_data_grpo/with_summary/test_cog.csv", index=False)

In [82]:
assert len(test_cog) == len(test)

## Amylpet

In [86]:
# Filter training data: exclude patients already used in NP task and keep only those with valid amyloid PET results
test_pet = (
    test
    .loc[
        (test['AMYLPET'].isin([0, 1]))
    ]
    .sample(frac=1, random_state=42)  # Shuffle all rows
    .reset_index(drop=True)
)

In [87]:
test_pet['AMYLPET'].value_counts()

AMYLPET
1.0    500
0.0    308
Name: count, dtype: int64

In [88]:
import random, string, json

# Keys related to amyloid biomarkers that should be removed from the patient summary
pet_keys_remove = [
    'Abnormally elevated amyloid on PET',
    'Abnormally low amyloid in CSF',
    'FDG-PET pattern of AD',
    'Tau PET evidence for AD',
    'Abnormally elevated CSF Tau or pTau'
]

pet_question_variants = [
    "Is the patient likely to have elevated amyloid pathology in the brain given the provided information?",
    "Does the patient likely have abnormal amyloid accumulation in the brain based on the clinical data?",
    "Based on the available information, is the patient likely amyloid positive in the brain?",
    "Does the evidence suggest the presence of elevated amyloid burden in the brain in this patient?",
    "Is there a high likelihood of underlying amyloid pathology in the brain based on the patient's profile?"
]


# Raw answer texts
PET_OPTION_TEXTS = ["Yes", "No"]

# Map AMYLPET value to answer text
PET_ANSWER_MAP = {
    1: "Yes",  # Amyloid positive
    0: "No",   # Amyloid negative
}

def add_pet_question(row, *, seed=None):
    rng = random.Random(seed if seed is not None else row.name)

    # 1️⃣ Choose a question variant randomly
    row['question'] = rng.choice(pet_question_variants)

    # 2️⃣ Remove sensitive fields from the summary
    json_file = json.loads(row['patient_summary'])
    for key in pet_keys_remove:
        if key in json_file.get('Imaging evidence', {}):
            json_file['Imaging evidence'].pop(key)
        if key in json_file.get('CSF evidence', {}):
            json_file['CSF evidence'].pop(key)
    row['patient_summary'] = json.dumps(json_file, indent=4)

    # 3️⃣ Shuffle the answer options
    shuffled = PET_OPTION_TEXTS.copy()
    rng.shuffle(shuffled)
    letters = list(string.ascii_uppercase[:len(shuffled)])
    row["options"] = "\n".join(f"{ltr}. {opt}" for ltr, opt in zip(letters, shuffled))

    # 4️⃣ Determine correct letter based on AMYLPET value
    correct_text = PET_ANSWER_MAP[row['AMYLPET']]
    correct_letter = letters[shuffled.index(correct_text)]
    row["ground_truth"] = correct_letter
    
    row['ground_truth_text'] = correct_text

    return row

In [89]:
# Apply the function across the PET training dataset
test_pet = test_pet.apply(add_pet_question, axis=1)

In [90]:
# Check distribution of amyloid PET labels
print(test_pet['AMYLPET'].value_counts())

# Quick check: How many times each question variant was picked
print(test_pet['question'].value_counts())

print(test_pet['ground_truth'].value_counts())

print(test_pet['ground_truth_text'].value_counts())

AMYLPET
1.0    500
0.0    308
Name: count, dtype: int64
question
Is the patient likely to have elevated amyloid pathology in the brain given the provided information?      168
Does the evidence suggest the presence of elevated amyloid burden in the brain in this patient?            163
Does the patient likely have abnormal amyloid accumulation in the brain based on the clinical data?        162
Based on the available information, is the patient likely amyloid positive in the brain?                   161
Is there a high likelihood of underlying amyloid pathology in the brain based on the patient's profile?    154
Name: count, dtype: int64
ground_truth
A    423
B    385
Name: count, dtype: int64
ground_truth_text
Yes    500
No     308
Name: count, dtype: int64

In [91]:
index = 0
print(test_pet.iloc[index]['options'])
print(test_pet.iloc[index]['ground_truth'])
print(test_pet.iloc[index]['ground_truth_text'])
print(test_pet.iloc[index]['AMYLPET'])

A. Yes
B. No
A
Yes
1.0

In [92]:
# Select only necessary columns
test_pet = test_pet[columns]

In [93]:
test_pet['Q_TYPE'] = 'Amyloid PET'

In [94]:
# print(train[train['NACCID'] == 'NACC867075'].iloc[0]['patient_summary'])

In [95]:
for key in pet_keys_remove:
    for i, row in test_pet.iterrows():
        if key in row['patient_summary']:
            print(i, key)
            # break

In [96]:
test_pet.to_csv(f"{directory_path}/training_data/testing_data_grpo/with_summary/test_pet_unmodified_summaries.csv", index=False)

## Amylcsf

In [97]:
# Filter training data: exclude patients already used in NP task and keep only those with valid amyloid PET results
test_csf = (
    test
    .loc[
        (test['AMYLCSF'].isin([0, 1]))
    ]
    .sample(frac=1, random_state=42)  # Shuffle all rows
    .reset_index(drop=True)
)

In [98]:
test_csf['AMYLCSF'].value_counts()

AMYLCSF
1.0    179
0.0    109
Name: count, dtype: int64

In [99]:
import random, string, json

# Keys related to amyloid biomarkers that should be removed from the patient summary
csf_keys_remove = [
    'Abnormally elevated amyloid on PET',
    'Abnormally low amyloid in CSF',
    'FDG-PET pattern of AD',
    'Tau PET evidence for AD',
    'Abnormally elevated CSF Tau or pTau'
]

csf_question_variants = [
    "Is the patient likely to have elevated amyloid pathology in the brain given the provided information?",
    "Does the patient likely have abnormal amyloid accumulation in the brain based on the clinical data?",
    "Based on the available information, is the patient likely amyloid positive in the brain?",
    "Does the evidence suggest the presence of elevated amyloid burden in the brain in this patient?",
    "Is there a high likelihood of underlying amyloid pathology in the brain based on the patient's profile?"
]


# Raw answer texts
CSF_OPTION_TEXTS = ["Yes", "No"]

# Map AMYLPET value to answer text
CSF_ANSWER_MAP = {
    1: "Yes",  # Amyloid positive
    0: "No",   # Amyloid negative
}

def add_csf_question(row, *, seed=None):
    rng = random.Random(seed if seed is not None else row.name)

    # 1️⃣ Choose a question variant randomly
    row['question'] = rng.choice(csf_question_variants)

    # 2️⃣ Remove sensitive fields from the summary
    json_file = json.loads(row['patient_summary'])
    for key in csf_keys_remove:
        if key in json_file.get('Imaging evidence', {}):
            json_file['Imaging evidence'].pop(key)
        if key in json_file.get('CSF evidence', {}):
            json_file['CSF evidence'].pop(key)
    row['patient_summary'] = json.dumps(json_file, indent=4)

    # 3️⃣ Shuffle the answer options
    shuffled = CSF_OPTION_TEXTS.copy()
    rng.shuffle(shuffled)
    letters = list(string.ascii_uppercase[:len(shuffled)])
    row["options"] = "\n".join(f"{ltr}. {opt}" for ltr, opt in zip(letters, shuffled))

    # 4️⃣ Determine correct letter based on AMYLPET value
    correct_text = CSF_ANSWER_MAP[row['AMYLCSF']]
    correct_letter = letters[shuffled.index(correct_text)]
    row["ground_truth"] = correct_letter
    
    row['ground_truth_text'] = correct_text

    return row

In [100]:
# Apply the function across the PET training dataset
test_csf = test_csf.apply(add_csf_question, axis=1)

In [101]:
# Check distribution of amyloid PET labels
print(test_csf['AMYLCSF'].value_counts())

# Quick check: How many times each question variant was picked
print(test_csf['question'].value_counts())

print(test_csf['ground_truth'].value_counts())

print(test_csf['ground_truth_text'].value_counts())

AMYLCSF
1.0    179
0.0    109
Name: count, dtype: int64
question
Is the patient likely to have elevated amyloid pathology in the brain given the provided information?      62
Does the evidence suggest the presence of elevated amyloid burden in the brain in this patient?            61
Is there a high likelihood of underlying amyloid pathology in the brain based on the patient's profile?    58
Does the patient likely have abnormal amyloid accumulation in the brain based on the clinical data?        56
Based on the available information, is the patient likely amyloid positive in the brain?                   51
Name: count, dtype: int64
ground_truth
B    146
A    142
Name: count, dtype: int64
ground_truth_text
Yes    179
No     109
Name: count, dtype: int64

In [102]:
index = 0
print(test_csf.iloc[index]['options'])
print(test_csf.iloc[index]['ground_truth'])
print(test_csf.iloc[index]['ground_truth_text'])
print(test_csf.iloc[index]['AMYLCSF'])

A. Yes
B. No
A
Yes
1.0

In [103]:
# Select only necessary columns
test_csf = test_csf[columns]

In [104]:
test_csf['Q_TYPE'] = 'Amyloid CSF'

In [105]:
# print(train[train['NACCID'] == 'NACC867075'].iloc[0]['patient_summary'])

In [106]:
for key in csf_keys_remove:
    for i, row in test_csf.iterrows():
        if key in row['patient_summary']:
            print(i, key)
            # break

In [107]:
test_csf.to_csv(f"{directory_path}/training_data/testing_data_grpo/with_summary/test_csf_unmodified_summaries.csv", index=False)

## DATSCAN

In [108]:
# Filter training data: exclude patients already used in NP task and keep only those with valid amyloid PET results
test_dat = (
    test
    .loc[
        (test['DATSCAN'].isin([0, 1]))
    ]
    .sample(frac=1, random_state=42)  # Shuffle all rows
    .reset_index(drop=True)
)

In [109]:
test_dat['DATSCAN'].value_counts()

DATSCAN
0.0    55
1.0    16
Name: count, dtype: int64

In [110]:
import random, string, json

# Keys related to DATScan that should be removed from the patient summary
dat_keys_remove = [
    'Dopamine transporter scan (DATscan) evidence for Lewy body disease'
]

dat_question_variants = [
    "Is there evidence of Lewy body disease in the brain based on the provided information?",
    "Does the provided information suggest the presence of Lewy body disease in the brain?",
    "Is the patient likely to have Lewy body pathology in the brain based on the available data?",
    "Based on the information given, is there evidence consistent with Lewy body disease in the brain?",
    "Does the information support the presence of underlying Lewy body pathology in the brain?"
]

# Raw answer texts
DAT_OPTION_TEXTS = ["Yes", "No"]

# Map DATSCAN value to answer text
DAT_ANSWER_MAP = {
    1: "Yes",  # DATScan positive
    0: "No",   # DATScan negative
}

def add_dat_question(row, *, seed=None):
    rng = random.Random(seed if seed is not None else row.name)

    # 1️⃣ Randomly assign a question variant
    row['question'] = rng.choice(dat_question_variants)

    # 2️⃣ Remove sensitive DATScan key from patient summary
    json_file = json.loads(row['patient_summary'])
    for key in dat_keys_remove:
        if key in json_file.get('Imaging evidence', {}):
            json_file['Imaging evidence'].pop(key)
    row['patient_summary'] = json.dumps(json_file, indent=4)

    # 3️⃣ Shuffle options
    shuffled = DAT_OPTION_TEXTS.copy()
    rng.shuffle(shuffled)
    letters = list(string.ascii_uppercase[:len(shuffled)])
    row["options"] = "\n".join(f"{ltr}. {opt}" for ltr, opt in zip(letters, shuffled))

    # 4️⃣ Determine correct letter based on DATSCAN value
    correct_text = DAT_ANSWER_MAP[row['DATSCAN']]
    correct_letter = letters[shuffled.index(correct_text)]
    
    row["ground_truth"] = correct_letter
    row['ground_truth_text'] = correct_text

    return row

In [111]:
test_dat = test_dat.apply(add_dat_question, axis=1)

In [112]:
# Check distribution of amyloid PET labels
print(test_dat['DATSCAN'].value_counts())

# Quick check: How many times each question variant was picked
print(test_dat['question'].value_counts())

print(test_dat['ground_truth'].value_counts())

print(test_dat['ground_truth_text'].value_counts())

DATSCAN
0.0    55
1.0    16
Name: count, dtype: int64
question
Based on the information given, is there evidence consistent with Lewy body disease in the brain?    17
Is there evidence of Lewy body disease in the brain based on the provided information?               16
Does the information support the presence of underlying Lewy body pathology in the brain?            15
Does the provided information suggest the presence of Lewy body disease in the brain?                14
Is the patient likely to have Lewy body pathology in the brain based on the available data?           9
Name: count, dtype: int64
ground_truth
B    37
A    34
Name: count, dtype: int64
ground_truth_text
No     55
Yes    16
Name: count, dtype: int64

In [113]:
index = 0
print(test_dat.iloc[index]['options'])
print(test_dat.iloc[index]['ground_truth'])
print(test_dat.iloc[index]['ground_truth_text'])
print(test_dat.iloc[index]['AMYLCSF'])

A. Yes
B. No
B
No
8.0

In [114]:
# Select only necessary columns
test_dat = test_dat[columns]

In [115]:
test_dat['Q_TYPE'] = 'DATSCAN'

In [116]:
# print(train[train['NACCID'] == 'NACC867075'].iloc[0]['patient_summary'])

In [117]:
for key in dat_keys_remove:
    for i, row in test_dat.iterrows():
        if key in row['patient_summary']:
            print(i, key)
            # break

In [118]:
test_dat.to_csv(f"{directory_path}/training_data/testing_data_grpo/with_summary/test_dat_unmodified_summaries.csv", index=False)