Created by: Varuna & Sahana

Date: Oct 2025

# Imports

In [1]:
import pandas as pd
import json
import numpy as np

# directory path

In [2]:
directory_path = '/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/ppmi'

# Main data

In [3]:
df = pd.read_csv(f'{directory_path}/test.csv')

In [4]:
df.head()

,SITE,PATNO,COHORT,subgroup,enroll_phase,HIQ_RBD,study_status,NSD_Status,NSD_STAGE,PRIMDIAG,...,ips_striatum,mean_striatum,Stage_partial_UPDRS1,Stage_subpark,Stage_PDTreat,Stage_S,Stage_D,Stage_G,patient_summary,diag_summary
0,10,3000,PPMI,Healthy Control,1,NaN,Active,NaN,NaN,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""Subject Demographics"": {""Age at Enrollment"":...","{""Most likely Primary Diagnosis"": ""No PD nor o..."
1,10,3001,PPMI,Sporadic PD,1,NaN,Active,1.0,4,1.0,...,NaN,NaN,24.0,NaN,1.0,1.0,1.0,NaN,"{""Subject Demographics"": {""Age at Enrollment"":...","{""Most likely Primary Diagnosis"": ""Idiopathic ..."
2,10,3002,PPMI,Sporadic PD,1,NaN,Active,1.0,5,1.0,...,NaN,NaN,15.0,NaN,1.0,1.0,1.0,NaN,"{""Subject Demographics"": {""Age at Enrollment"":...","{""Most likely Primary Diagnosis"": ""Idiopathic ..."
3,10,3003,PPMI,Sporadic PD,1,NaN,Active,1.0,4,1.0,...,NaN,NaN,15.0,NaN,1.0,1.0,1.0,NaN,"{""Subject Demographics"": {""Age at Enrollment"":...","{""Most likely Primary Diagnosis"": ""Idiopathic ..."
4,10,3004,PPMI,Healthy Control,1,NaN,Active,NaN,NaN,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""Subject Demographics"": {""Age at Enrollment"":...","{""Most likely Primary Diagnosis"": ""No PD nor o..."

# GAMLSS data

In [5]:
# gamlss_data = pd.read_csv('/projectnb/vkolagrp/projects/adrd_foundation_model/image_proc/gamlss_data/gamlss_thresholded_wtext_wmetadata.csv')
gamlss_data = pd.read_csv('/projectnb/vkolagrp/projects/adrd_foundation_model/image_proc/gamlss_data/gamlss_thresholded_wtext_wmetadata_0805.csv')
ppmi_gamlss = gamlss_data[gamlss_data['COHORT'] == 'PPMI']
# ppmi_gamlss.drop(columns=['DX'], inplace=True) # DX is a manually recoded variable that i used for QC purposes
ppmi_gamlss.head()

,ID,COHORT,NACCAGE,SEX,DX,brain_findings_summary
0,PPMI_100232,PPMI,64.0,2.0,CN,Medial Parietal region has mild atrophy; Front...
1,PPMI_100677,PPMI,63.0,2.0,CN,Hippocampus region has severe atrophy; Medial ...
2,PPMI_100712,PPMI,65.0,2.0,CN,No significant findings. Brain MRI appears age...
3,PPMI_100890,PPMI,78.0,1.0,CN,No significant findings. Brain MRI appears age...
4,PPMI_100960,PPMI,66.0,2.0,CN,No significant findings. Brain MRI appears age...

In [6]:
ppmi_gamlss['PATNO'] = ppmi_gamlss['ID'].str.split('PPMI_').str[1]

/scratch/ipykernel_3043436/2022238529.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ppmi_gamlss['PATNO'] = ppmi_gamlss['ID'].str.split('PPMI_').str[1]

In [7]:
df['PATNO'] = df['PATNO'].astype('int')
ppmi_gamlss['PATNO'] = ppmi_gamlss['PATNO'].astype('int')

/scratch/ipykernel_3043436/1111040668.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ppmi_gamlss['PATNO'] = ppmi_gamlss['PATNO'].astype('int')

In [8]:
merged_df = pd.merge(df, ppmi_gamlss[['PATNO', 'brain_findings_summary']], on =['PATNO'], how = 'left')

In [9]:
merged_df.head()

,SITE,PATNO,COHORT,subgroup,enroll_phase,HIQ_RBD,study_status,NSD_Status,NSD_STAGE,PRIMDIAG,...,mean_striatum,Stage_partial_UPDRS1,Stage_subpark,Stage_PDTreat,Stage_S,Stage_D,Stage_G,patient_summary,diag_summary,brain_findings_summary
0,10,3000,PPMI,Healthy Control,1,NaN,Active,NaN,NaN,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""Subject Demographics"": {""Age at Enrollment"":...","{""Most likely Primary Diagnosis"": ""No PD nor o...",No significant findings. Brain MRI appears age...
1,10,3001,PPMI,Sporadic PD,1,NaN,Active,1.0,4,1.0,...,NaN,24.0,NaN,1.0,1.0,1.0,NaN,"{""Subject Demographics"": {""Age at Enrollment"":...","{""Most likely Primary Diagnosis"": ""Idiopathic ...",Medial Parietal region has moderate atrophy
2,10,3002,PPMI,Sporadic PD,1,NaN,Active,1.0,5,1.0,...,NaN,15.0,NaN,1.0,1.0,1.0,NaN,"{""Subject Demographics"": {""Age at Enrollment"":...","{""Most likely Primary Diagnosis"": ""Idiopathic ...",Medial Parietal region has moderate atrophy
3,10,3003,PPMI,Sporadic PD,1,NaN,Active,1.0,4,1.0,...,NaN,15.0,NaN,1.0,1.0,1.0,NaN,"{""Subject Demographics"": {""Age at Enrollment"":...","{""Most likely Primary Diagnosis"": ""Idiopathic ...",Medial Parietal region has mild atrophy; Later...
4,10,3004,PPMI,Healthy Control,1,NaN,Active,NaN,NaN,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""Subject Demographics"": {""Age at Enrollment"":...","{""Most likely Primary Diagnosis"": ""No PD nor o...",No significant findings. Brain MRI appears age...

In [10]:
print(merged_df['patient_summary'].iloc[0])

{"Subject Demographics": {"Age at Enrollment": 69.1397260273973, "Age at Visit": 79.4191780821918, "Sex at birth": "Female", "Years of Education capped at 20": 18, "Race": "White", "Indicator for Hispanic/Latino ethnicity": "No", "Indicator for Ashkenazi Jewish descent": "No", "Indicator for African Berber descent": "No", "Indicator for Basque descent": "No", "Handedness": "Right"}, "Subject Family History": {"Family History of PD - 3 categories.": "No Family w/PD", "Family History of PD - Binary": "No Family w/PD"}, "Subject Medications": {"Is the participant on dopaminergic medication or receiving deep brain stimulation for treating the symptoms of Parkinsons disease?": "No", "Total Levodopa Equivalent Daily Dose": 0.0}, "Physical": {"Body Mass Index": 52.8925619834711, "Indicator of whether systolic blood pressure change is greater or equal to 20 OR diastolic blood pressure change is greater than or equal to 10.": "No"}, "Unified Parkinson's Disease Rating Scale (UPDRS)": {"Hoehn & Yahr Stage (includes OFF and untreated scores)": "Stage 0", "Hoehn & Yahr Stage (includes ON and untreated scores)": "Stage 0", "MDS-UPDRS Part I Cognitive Impairment": "Normal", "MDS-UPDRS Part I Hallucinations and Psychosis": "Normal", "MDS-UPDRS Part I Depressed Mood": "Slight", "MDS-UPDRS Part I Anxious Mood": "Normal", "MDS-UPDRS Part I Apathy": "Normal", "MDS-UPDRS Part I Features of Dopamine Dysregulation Syndrome": "Normal", "MDS-UPDRS Part I Fatigue": "Normal", "MDS-UPDRS Part I Score": 5, "MDS-UPDRS Part II Score": 0, "MDS-UPDRS Part III Score OFF (includes OFF and untreated scores)": 3, "MDS-UPDRS Part III Score ON (includes ON and untreated scores)": 3, "MDS-UPDRS Total Score OFF (includes OFF and untreated scores)": 8, "MDS-UPDRS Total Score ON (includes ON and untreated scores)": 8}, "Geriatric Depression Scale (GDS)": {"Geriatric Depression Scale Score": 1}, "Activities of Daily Living": {"Modified Schwab & England ADL Score": 95}, "Sleep Questionnaire": {"Epworth Sleepiness Scale Score": 3, "REM Sleep Behavior Disorder Questionnaire Score": 0}, "Anxiety Questionnaire": {"STAI Total Score": 58, "STAI State Sub-score": 32, "STAI Trait Sub-score": 26}, "Scales for Outcomes in Parkinson's Disease": {"SCOPA-AUT Total Score": 8, "SCOPA-AUT Gastrointestinal (GI) Score": 1, "SCOPA-AUT Urinary Score": 7, "SCOPA-AUT Cardiovascular Score": 0, "SCOPA-AUT Thermoregulatory Score": 0, "SCOPA-AUT Pupillomotor Score": 0, "SCOPA-AUT Sexual Dysfunction Score": 0}, "Neuropsychological Battery Summary Scores": {"MOCA Score (adjusted for education)": 26, "Benton Judgement of Line Orientation Score": 14, "Total Clock Drawing Score": 7, "HVLT Discrimination Recognition": 7, "HVLT Immediate/Total Recall": 21, "HVLT Retention": 0.5, "HVLT False Alarms": 0, "HVLT Delayed Recall ": 4, "HVLT Delayed Recognition": 8, "Lexical Fluency Score": 36, "Letter Number Sequencing Score": 13, "Modified Boston Naming Test Score": 50, "Symbol Digit Modalities Score": 44, "Time (in seconds) to complete Trails Making Test - A": 35.0, "Time (in seconds) to complete Trails Making Test - B": 85.0, "Semantic Fluency Score - Animal subscore": 16}, "Genetics": {"APOE genotype": "e3/e3", "Number of E4 alleles in APOE genotype": 0}}

In [11]:
def add_mri_report(row):
    """Add MRI Report section to mapped_json"""
    # Parse the JSON string to a dictionary
    data = json.loads(row['patient_summary'])
    if pd.notna(row['brain_findings_summary']):
        # Create the MRI Report section
        mri_report = {
            "MRI Report": {
                "MRI features extraction procedure": "A Generalized Additive Model for Location, Scale, and Shape (GAMLSS) was fitted to FastSurfer-derived regional brain volumes acquired from 2,087 healthy controls, following the Brain charts for the human lifespan methodology published in Nature (2022). Data were aggregated from five independent cohorts, and the analysis included region-of-interest (ROI) volumes for the medial and lateral temporal lobes, medial and lateral parietal lobes, frontal, occipital lobes, as well as the inferior lateral ventricles and hippocampus. To ensure a robust normative reference, participants with any known neurodegenerative disease were excluded and subjects with extreme brain volumes (>3.5 absolute z-scores) were excluded during quality control prior to model fitting. The Brain Charts pipeline was implemented to model age- and sex-specific normative centile curves for each ROI. Centile scores (scaled 0-1) were computed for both healthy controls and patient samples. Abnormality was defined based on a one-sided z-score threshold: mild atrophy/enlargement for scores corresponding to 1 standard deviation (z=1), moderate for 1.5 SD (z=1.5), and severe for 2 SD (z=2). For all lobar ROIs, lower centiles indicated greater atrophy, while for ventricular ROIs, higher centiles indicated enlargement (i.e., abnormality). The resulting findings are as follows: ",
                "T1 MRI Findings": str(row['brain_findings_summary'])
            }
        }
        
        if 'Imaging evidence' not in data.keys():
            data['Imaging evidence'] = mri_report
        else:
            # Add the MRI Report to the data
            data['Imaging evidence'].update(mri_report)
    
    # Convert back to JSON string
    return json.dumps(data)

In [12]:
merged_df['patient_summary'] = merged_df.apply(add_mri_report, axis=1)

In [13]:
print(merged_df['patient_summary'].iloc[0])

{"Subject Demographics": {"Age at Enrollment": 69.1397260273973, "Age at Visit": 79.4191780821918, "Sex at birth": "Female", "Years of Education capped at 20": 18, "Race": "White", "Indicator for Hispanic/Latino ethnicity": "No", "Indicator for Ashkenazi Jewish descent": "No", "Indicator for African Berber descent": "No", "Indicator for Basque descent": "No", "Handedness": "Right"}, "Subject Family History": {"Family History of PD - 3 categories.": "No Family w/PD", "Family History of PD - Binary": "No Family w/PD"}, "Subject Medications": {"Is the participant on dopaminergic medication or receiving deep brain stimulation for treating the symptoms of Parkinsons disease?": "No", "Total Levodopa Equivalent Daily Dose": 0.0}, "Physical": {"Body Mass Index": 52.8925619834711, "Indicator of whether systolic blood pressure change is greater or equal to 20 OR diastolic blood pressure change is greater than or equal to 10.": "No"}, "Unified Parkinson's Disease Rating Scale (UPDRS)": {"Hoehn & Yahr Stage (includes OFF and untreated scores)": "Stage 0", "Hoehn & Yahr Stage (includes ON and untreated scores)": "Stage 0", "MDS-UPDRS Part I Cognitive Impairment": "Normal", "MDS-UPDRS Part I Hallucinations and Psychosis": "Normal", "MDS-UPDRS Part I Depressed Mood": "Slight", "MDS-UPDRS Part I Anxious Mood": "Normal", "MDS-UPDRS Part I Apathy": "Normal", "MDS-UPDRS Part I Features of Dopamine Dysregulation Syndrome": "Normal", "MDS-UPDRS Part I Fatigue": "Normal", "MDS-UPDRS Part I Score": 5, "MDS-UPDRS Part II Score": 0, "MDS-UPDRS Part III Score OFF (includes OFF and untreated scores)": 3, "MDS-UPDRS Part III Score ON (includes ON and untreated scores)": 3, "MDS-UPDRS Total Score OFF (includes OFF and untreated scores)": 8, "MDS-UPDRS Total Score ON (includes ON and untreated scores)": 8}, "Geriatric Depression Scale (GDS)": {"Geriatric Depression Scale Score": 1}, "Activities of Daily Living": {"Modified Schwab & England ADL Score": 95}, "Sleep Questionnaire": {"Epworth Sleepiness Scale Score": 3, "REM Sleep Behavior Disorder Questionnaire Score": 0}, "Anxiety Questionnaire": {"STAI Total Score": 58, "STAI State Sub-score": 32, "STAI Trait Sub-score": 26}, "Scales for Outcomes in Parkinson's Disease": {"SCOPA-AUT Total Score": 8, "SCOPA-AUT Gastrointestinal (GI) Score": 1, "SCOPA-AUT Urinary Score": 7, "SCOPA-AUT Cardiovascular Score": 0, "SCOPA-AUT Thermoregulatory Score": 0, "SCOPA-AUT Pupillomotor Score": 0, "SCOPA-AUT Sexual Dysfunction Score": 0}, "Neuropsychological Battery Summary Scores": {"MOCA Score (adjusted for education)": 26, "Benton Judgement of Line Orientation Score": 14, "Total Clock Drawing Score": 7, "HVLT Discrimination Recognition": 7, "HVLT Immediate/Total Recall": 21, "HVLT Retention": 0.5, "HVLT False Alarms": 0, "HVLT Delayed Recall ": 4, "HVLT Delayed Recognition": 8, "Lexical Fluency Score": 36, "Letter Number Sequencing Score": 13, "Modified Boston Naming Test Score": 50, "Symbol Digit Modalities Score": 44, "Time (in seconds) to complete Trails Making Test - A": 35.0, "Time (in seconds) to complete Trails Making Test - B": 85.0, "Semantic Fluency Score - Animal subscore": 16}, "Genetics": {"APOE genotype": "e3/e3", "Number of E4 alleles in APOE genotype": 0}, "Imaging evidence": {"MRI Report": {"MRI features extraction procedure": "A Generalized Additive Model for Location, Scale, and Shape (GAMLSS) was fitted to FastSurfer-derived regional brain volumes acquired from 2,087 healthy controls, following the Brain charts for the human lifespan methodology published in Nature (2022). Data were aggregated from five independent cohorts, and the analysis included region-of-interest (ROI) volumes for the medial and lateral temporal lobes, medial and lateral parietal lobes, frontal, occipital lobes, as well as the inferior lateral ventricles and hippocampus. To ensure a robust normative reference, participants with any known neurodegenerative disease were excluded and subjects with extreme brain volumes (>3.5 absolute z-scores) were excluded during quality control prior to model fitting. The Brain Charts pipeline was implemented to model age- and sex-specific normative centile curves for each ROI. Centile scores (scaled 0-1) were computed for both healthy controls and patient samples. Abnormality was defined based on a one-sided z-score threshold: mild atrophy/enlargement for scores corresponding to 1 standard deviation (z=1), moderate for 1.5 SD (z=1.5), and severe for 2 SD (z=2). For all lobar ROIs, lower centiles indicated greater atrophy, while for ventricular ROIs, higher centiles indicated enlargement (i.e., abnormality). The resulting findings are as follows: ", "T1 MRI Findings": "No significant findings. Brain MRI appears age-appropriate."}}}

In [14]:
# merged_df.to_csv('/projectnb/vkolagrp/projects/adrd_foundation_model/json_testing_data/ppmi_oct_2025.csv', index=False)

In [15]:
json.loads(merged_df[merged_df['PATNO'] == 4066].iloc[0]['patient_summary'])

{'Subject Demographics': {'Age at Enrollment': 60.8630136986301,
  'Age at Visit': 60.8630136986301,
  'Sex at birth': 'Male',
  'Years of Education capped at 20': 20,
  'Race': 'White',
  'Indicator for Hispanic/Latino ethnicity': 'No',
  'Handedness': 'Right'},
 'Subject Family History': {'Family History of PD - 3 categories.': 'No Family w/PD',
  'Family History of PD - Binary': 'No Family w/PD'},
 'Subject Medications': {'Is the participant on dopaminergic medication or receiving deep brain stimulation for treating the symptoms of Parkinsons disease?': 'No',
  'Total Levodopa Equivalent Daily Dose': 0.0},
 'Physical': {'Body Mass Index': 25.4716077755434,
  'Indicator of whether systolic blood pressure change is greater or equal to 20 OR diastolic blood pressure change is greater than or equal to 10.': 'No'},
 "Unified Parkinson's Disease Rating Scale (UPDRS)": {'Hoehn & Yahr Stage (includes OFF and untreated scores)': 'Stage 2',
  'Hoehn & Yahr Stage (includes ON and untreated scores)': 'Stage 2',
  'MDS-UPDRS Part I Cognitive Impairment': 'Normal',
  'MDS-UPDRS Part I Hallucinations and Psychosis': 'Normal',
  'MDS-UPDRS Part I Depressed Mood': 'Normal',
  'MDS-UPDRS Part I Anxious Mood': 'Normal',
  'MDS-UPDRS Part I Apathy': 'Normal',
  'MDS-UPDRS Part I Features of Dopamine Dysregulation Syndrome': 'Normal',
  'MDS-UPDRS Part I Fatigue': 'Normal',
  'MDS-UPDRS Part I Score': 2,
  'MDS-UPDRS Part II Score': 2,
  'MDS-UPDRS Part III Score OFF (includes OFF and untreated scores)': 19,
  'MDS-UPDRS Part III Score ON (includes ON and untreated scores)': 19,
  'MDS-UPDRS Total Score OFF (includes OFF and untreated scores)': 23,
  'MDS-UPDRS Total Score ON (includes ON and untreated scores)': 23},
 'Geriatric Depression Scale (GDS)': {'Geriatric Depression Scale Score': 6},
 'Activities of Daily Living': {'Modified Schwab & England ADL Score': 100},
 'Sleep Questionnaire': {'Epworth Sleepiness Scale Score': 0,
  'REM Sleep Behavior Disorder Questionnaire Score': 2},
 'Anxiety Questionnaire': {'STAI Total Score': 56,
  'STAI State Sub-score': 28,
  'STAI Trait Sub-score': 28},
 "Scales for Outcomes in Parkinson's Disease": {'SCOPA-AUT Total Score': 4,
  'SCOPA-AUT Gastrointestinal (GI) Score': 0,
  'SCOPA-AUT Urinary Score': 1,
  'SCOPA-AUT Cardiovascular Score': 0,
  'SCOPA-AUT Thermoregulatory Score': 1,
  'SCOPA-AUT Pupillomotor Score': 1,
  'SCOPA-AUT Sexual Dysfunction Score': 1},
 'Neuropsychological Battery Summary Scores': {'MOCA Score (adjusted for education)': 28,
  'Benton Judgement of Line Orientation Score': 10,
  'HVLT Discrimination Recognition': 9,
  'HVLT Immediate/Total Recall': 26,
  'HVLT Retention': 0.5,
  'HVLT False Alarms': 1,
  'HVLT Delayed Recall ': 5,
  'HVLT Delayed Recognition': 10,
  'Letter Number Sequencing Score': 9,
  'Symbol Digit Modalities Score': 30,
  'Semantic Fluency Score - Animal subscore': 17},
 'Genetics': {'APOE genotype': 'e3/e3',
  'Number of E4 alleles in APOE genotype': 0},
 'CSF Biomarkers': {'CSF A-beta 1-42 (combined 2016/2021 assays)': 626.5,
  'Indicates whether CSF A-beta 1-42 test result was below the LOWER limit of detection (< 200 pg/mL)': 'No',
  'Indicates whether CSF A-beta 1-42 test result was equal to or above the UPPER limit of detection (>= 1475.4 pg/mL)': 'No',
  'CSF t-tau (combined 2016/2021 assays)': 114.6,
  'Indicates whether CSF t-tau test result was equal to or below the LOWER limit of detection (<= 80 pg/mL)': 'No',
  'CSF p-tau (combined 2016/2021 assays)': 8.75,
  'Indicates whether CSF p-tau test result was equal to or below the LOWER limit of detection (<= 8 pg/mL)': 'No',
  'Indicator of high CSF hemoglobin (2016 assay)': '<200 '},
 'Blood Biomarkers': {'Serum Uric Acid (mg/dL)': 8.0},
 'Imaging evidence': {'DATSCAN': {'DATSCAN Age-/Sex-expected Lowest Putamen ratio': 0.387978604616347,
   'Left caudate': 1.36,
   'Right caudate': 1.4,
   'Contralateral caudate': 1.4,
   'Ipsliateral caudate': 1.36,
   'Mean caudate measure': 1.38,
   'Left putamen': 0.76,
   'Right putamen': 0.8,
   'Contralateral putamen': 0.8,
   'Ipsilateral putamen': 0.76,
   'Mean putamen measure': 0.78,
   'Contralateral striatum': 2.2,
   'Ipsilateral striatum': 2.12,
   'Mean striatum measure': 1.08,
   'Visit-level DAT SBR status - indicates whether age-/sex-expected DaT ratio is < 0.75': 'Yes'},
  'MRI Report': {'MRI features extraction procedure': 'A Generalized Additive Model for Location, Scale, and Shape (GAMLSS) was fitted to FastSurfer-derived regional brain volumes acquired from 2,087 healthy controls, following the Brain charts for the human lifespan methodology published in Nature (2022). Data were aggregated from five independent cohorts, and the analysis included region-of-interest (ROI) volumes for the medial and lateral temporal lobes, medial and lateral parietal lobes, frontal, occipital lobes, as well as the inferior lateral ventricles and hippocampus. To ensure a robust normative reference, participants with any known neurodegenerative disease were excluded and subjects with extreme brain volumes (>3.5 absolute z-scores) were excluded during quality control prior to model fitting. The Brain Charts pipeline was implemented to model age- and sex-specific normative centile curves for each ROI. Centile scores (scaled 0-1) were computed for both healthy controls and patient samples. Abnormality was defined based on a one-sided z-score threshold: mild atrophy/enlargement for scores corresponding to 1 standard deviation (z=1), moderate for 1.5 SD (z=1.5), and severe for 2 SD (z=2). For all lobar ROIs, lower centiles indicated greater atrophy, while for ventricular ROIs, higher centiles indicated enlargement (i.e., abnormality). The resulting findings are as follows: ',
   'T1 MRI Findings': 'Medial Parietal region has moderate atrophy; Inferior Ventricles region has severe enlargement'}}}

In [16]:
merged_df.to_csv(f'{directory_path}/test_gamlss.csv', index=False)